local Data = {
	['ASH'] = {
		{
			Name = 'Shuriken',
			{'STR * 500', 'Base damage', },
			{'STR * 500 * 0.4375', Unit = '/s', 'Bleed DoT', },
			{'STR * 500 * 5.37', 'Total damage', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Seeking Shuriken',
			AUG = true,
			{'DUR * 8', Unit = 's', 'Debuff duration', },
			{'STR * 70', Unit = '%', 'Armor reduction', },
		},
		{
			Name = 'Smoke Screen',
			{'DUR * 8', Unit = 's', 'Duration', },
			{'RNG * 10', Unit = 'm', 'Range', },
			{'(2 - EFF) * 35', 'Energy', },
		},
		{
			Name = 'Teleport',
			{'RNG * 15', Unit = 'm', 'Range', },
		},
		{
			Name = 'Fatal Teleport',
			AUG = true,
			{'RNG * 60', Unit = 'm', 'Bonus damage', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Blade Storm',
			{'STR * 2000', 'Base damage', },
			{(2000*0.35*1.25)..'*STR', Unit = "/s", 'Bleed DoT'},
            {(2000*(1 + 0.35*1.25*9))..'*STR', 'Total Damage'},
            {'60*RNG', Unit = "m", 'Range'},
            {'12* (2 - EFF)', 'Energy per Mark'},
            {'6* (2 - EFF)', 'Energy per Mark While Invisible'},
		},
		{
			Name = 'Rising Storm',
			AUG = true,
			{'STR * 4', 'Combo per Hit', },
		},
	},
	['ATLAS'] = {
		{
			Name = 'Landslide',
			{'STR * 350 * COMBO', 'Damage', },
			{'DUR', Unit = 's', 'Combo window', },
			{'RNG * 15', Unit = 'm', 'Dash range', },
			{'RNG * 2 * Math.min(3, COMBO)', Unit = 'm', 'Impact radius', },
			{'(2 - EFF) * 25 * (1 / COMBO)', 'Energy', },
		},
		{
			Name = 'Path Of Statues',
			AUG = true,
			{'DUR * 7', Unit = 's', 'Path duration', },
			{'DUR * 14', Unit = 's', 'Petrify duration', },
		},
		{
			Name = 'Tectonics',
			{'3750 + 5 * (450 * xARMOR * STR + aARMOR)', 'Health', },
			{'STR * 600', 'Roll damage', },
			{'STR * 500', 'Explosion damage', },
			{'RNG * 5', Unit = 'm', 'Explosion radius', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Petrify',
			{'DUR * 20', Unit = 's', 'Petrify duration', },
			{'RNG * 14', Unit = 'm', 'Cone length', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Ore Gaze',
			AUG = true,
			{'STR * 25, 100', Unit = '%', 'Loot chance', },
		},
		{
			Name = 'Rumblers',
			{'45 * DUR', Unit = 's', 'Duration', },
			{'1200 * (4 + HEALTH + SHIELDS + STR)', 'Health', },
			{'500 * (xARMOR + STR) + aARMOR', 'Armor', },
			{'STR * 2000', 'Melee damage', },
			{'STR * 500', 'Rock damage', },
			{'STR * 1250', 'Explosion damage', },
			{'RNG * 6', Unit = 'm', 'Stone/Explosion radius', },
			{'(2 - EFF) * 100', 'Speed multiplier', },
		},
		{
			Name = 'Titanic Rumbler',
			AUG = true,
		},
	},
	['BANSHEE'] = {
		{
			Name = 'Sonic Boom',
			{'STR * 50', 'Damage', },
			{'RNG * 15', Unit = 'm', 'Cone length', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Sonic Fracture',
			AUG = true,
			{'(STR * 70), 100', Unit = '%', 'Armor reduction', },
			{'DUR * 8', Unit = 's', 'Debuff duration', },
		},
		{
			Name = 'Sonar',
			{'DUR * 30', Unit = 's', 'Duration', },
			{'STR * 5', Unit = 'x', 'Damage multiplier', },
			{'RNG * 35', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Silence',
			{'DUR * 30', Unit = 's', 'Duration', },
			{'RNG * 20', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Savage Silence',
			AUG = true,
			{'STR * 3', Unit = 'x', 'Damage multiplier', },
		},
		{
			Name = 'Sound Quake',
			{'STR * 200', Unit = '/s', 'Damage', },
			{'RNG * 20', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
			{'CHA * 12', Unit = '/s', 'Energy drain', },
		},
		{
			Name = 'Resonating Quake',
			AUG = true,
		},
	},
	['BARUUK'] = {
		{
			Name = 'Elude',
			{'(RNG * 180), 360', Unit = '°', 'Evasion angle', },
			{'(2 - EFF) * 25', 'Energy', },
			{'CHA * 2.5', Unit = '/s', 'Energy drain', },
		},
		{
			Name = 'Lull',
			{'DUR * 5', Unit = 's', 'Wave duration', },
			{'DUR * 25', Unit = 's', 'Sleep duration', },
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Desolate Hands',
			{'STR * 250', 'Damage', },
			{'STR * 8', 'Charges', },
			{'((STR * 8', Unit = '%', 'Damage reduction', },
			{'RNG * 6', Unit = 'm', 'Seek range', },
			{'RNG * 3', Unit = 'm', 'Explosion range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Serene Storm',
		},
	},
	['CHROMA'] = {
        Types = {"Element", "Heat", "Electric", "Toxin", "Cold"},
        {
            Name = 'Spectral Scream',
            {'200*STR', 'Damage per Second'},
            {'10*RNG', Unit = "m", 'Range'},
            {'10*(2 - EFF)', 'Energy'},
            {'3*(2 - EFF)/DUR', Unit = "/s", 'Energy Drain'},
        },
        {
            Name = 'Afterburn',
            AUG = true,
            {'500*STR', 'Damage'},
        },
        {
            Name = 'Elemental Ward',
            Type = 'Heat',
            {'40*DUR', Unit = "s", 'Duration'},
            {'100*STR', 'Damage per Second'},
            {'200*STR', Unit = "%", 'Health Bonus'},
            {'15*RNG', Unit = "m", 'Aura Range'},
            {'50*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Elemental Ward',
            Type = 'Electric',
            {'40*DUR', Unit = "s", 'Duration'},
            {'10*STR', Unit = "x", 'Reflection Multiplier'},
            {'100*STR', Unit = "%", 'Shield Bonus'},
            {'25*STR', Unit = "%", 'Status Chance'},
            {'200*STR', 'Minimum Arc Damage'},
            {'15*RNG', Unit = "m", 'Aura Range'},
            {'15*RNG', Unit = "m", 'Discharge Range'},
            {'50*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Elemental Ward',
            Type = 'Cold',
            {'40*DUR', Unit = "s", 'Duration'},
            {'3*STR', Unit = "x", 'Reflection Multiplier'},
            {'150*STR', Unit = "%", 'Armor Bonus'},
            {'25*STR', Unit = "%", 'Status Chance'},
            {'15*RNG', Unit = "m", 'Aura Range'},
            {'50*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Elemental Ward',
            Type = 'Toxin',
            {'40*DUR', Unit = "s", 'Duration'},
            {'35*STR', Unit = "%", 'Holster/Reload Bonus'},
            {'50*STR', Unit = "%", 'Damage Chance'},
            {'15*RNG', Unit = "m", 'Aura Range'},
            {'50*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Everlasting Ward',
            AUG = true,
        },
        {
            Name = 'Vex Armor',
            {'350*STR', Unit = "%", 'Maximum Armor Bonus'},
            {'275*STR', Unit = "%", 'Maximum Damage Bonus'},
            {'25*DUR', Unit = "s", 'Duration'},
            {'18*RNG', Unit = "m", 'Range'},
            {'75*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Vexing Retaliation',
            AUG = true,
            {'9*RNG', Unit = "m", 'Range'},
        },
        {
            Name = 'Effigy',
            {'2000*STR', 'Damage per Second'},
            {'8000*STR', 'Health'},
            {'10*(2 - EFF)', 'Energy'},
            {'10*(2 - EFF)/DUR', 'Energy per Second'},
        },
        {
            Name = 'Guided Effigy',
            AUG = true,
            {'2000*STR', 'Damage per Second'},
        },
    },
	['EMBER'] = {
		{
			Name = 'Fireball',
			{'STR * 400', Unit = ' - ', 'Impact Damage', },
			{'STR * 150', Unit = ' - ', 'Area Damage', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Fireball Frenzy',
			AUG = true,
			{'STR * 100', Unit = '%', 'Damage bonus', },
			{'DUR * 40', Unit = 's', 'Duration', },
			{'RNG * 15', Unit = 'm', 'Range', },
		},
		{
			Name = 'Accelerant',
			{'STR * 2.5', Unit = 'x', 'Fire damage multiplier', },
			{'DUR * 30', Unit = 's', 'Duration', },
			{'RNG * 20', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Flash Accelerant',
			AUG = true,
			{'STR * 0.5', Unit = 'x', 'Fire damage multiplier', },
		},
		{
			Name = 'Fire Blast',
			{'STR * 200', 'Wave damage', },
			{'STR * 225', Unit = '/s', 'Ring damage', },
			{'DUR * 20', Unit = 's', 'Duration', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'World On Fire',
		},
	},
	['EQUINOX'] = {
        Types = {"Form", "Night", "Day"},
        {
            Name = 'Metamorphosis',
            Type = 'Night',
            {'250*STR', 'Armor Bonus'},
            {'150*STR', 'Shield Bonus'},
            {'30*DUR', Unit = "s", 'Duration'},
            {'25*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Metamorphosis',
            Type = 'Day',
            {'25*STR', Unit = "%", 'Damage Bonus'},
            {'15*STR', Unit = "%", 'Speed Bonus'},
            {'30*DUR', Unit = "s", 'Duration'},
            {'25*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Duality',
            AUG = true,
            {'10*DUR', Unit = "s", 'Duration'},
        },
        {
            Name = 'Rest & Rage',
            Type = 'Night',
            {'22*DUR', Unit = "s", 'Duration'},
            {'5*RNG', Unit = "m", 'Cast Range'},
            {'50*RNG', Unit = "m", 'Area Range'},
            {'25*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Rest & Rage',
            Type = 'Day',
            {'50*STR', Unit = "%", 'Damage Vulnerability'},
            {'20*STR', Unit = "%", 'Enemy Speed Bonus'},
            {'22*DUR', Unit = "s", 'Duration'},
            {'5*RNG', Unit = "m", 'Cast Range'},
            {'50*RNG', Unit = "m", 'Area Range'},
            {'25*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Calm & Frenzy',
            AUG = true,
            {'5*RNG', Unit = "m", 'Diffusion Range'},
        },
        {
            Name = 'Pacify & Provoke',
            Type = 'Night',
            {'50*STR', Unit = "%", 'Enemy Damage Reduction'},
            {'16*RNG', Unit = "m", 'Range'},
            {'10*(2 - EFF)', 'Energy'},
            {'0.5*(2 - EFF)', Unit = "/s", 'Energy Drain per Enemy'},
        },
        {
            Name = 'Peaceful Provocation',
            Type = 'Night',
            AUG = true,
            {'40*STR', Unit = "%", 'Max Enemy Speed Reduction'},
        },
        {
            Name = 'Pacify & Provoke',
            Type = 'Day',
            {'20*STR', Unit = "%", 'Ability Strength Bonus'},
            {'16*RNG', Unit = "m", 'Range'},
            {'10*(2 - EFF)', 'Energy'},
            {'3*(2 - EFF)', Unit = "/s", 'Energy Drain per Ability'},
        },
        {
            Name = 'Peaceful Provocation',
            Type = 'Day',
            AUG = true,
            {'35*STR', Unit = "%", 'Ability Strength Bonus'},
        },
        {
            Name = 'Mend & Maim',
            Type = 'Night',
            {'25*STR', 'Shields per Kill'},
            {'18*RNG', Unit = "m", 'Range'},
            {'50*(2 - EFF)', 'Energy'},
            {'3.5*(2 - EFF)/DUR', 'Energy per Second'},
        },
        {
            Name = 'Mend & Maim',
            Type = 'Day',
            {'150*STR', 'Aura Damage'},
            {'18*RNG', Unit = "m", 'Range'},
            {'50*(2 - EFF)', 'Energy'},
            {'3.5*(2 - EFF)/DUR', 'Energy per Second'},
        },
        {
            Name = 'Energy Transfer',
            AUG = true,
        },
    },
    ['EXCALIBUR'] = {
		{
			Name = 'Slash Dash',
			{'STR * 250', 'Damage', },
			{'RNG * 12', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Surging Dash',
			AUG = true,
			{'(STR * 4 + 1) * TARGET', 'Combo counter hits', },
		},
		{
			Name = 'Radial Blind',
			{'DUR * 15', Unit = 's', 'Duration', },
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Radial Finish',
			AUG = true,
			{'STR * 300', Unit = '%', 'Damage multiplier', },
		},
		{
			Name = 'Radial Javelin',
			{'STR * 1000', 'Damage', },
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Furious Javelin',
			AUG = true,
			{'STR * 10 * Math.min(TARGET, 12)', Unit = '%', 'Bonus melee damage', },
			{'DUR * 16', Unit = 's', 'Buff duration', },
		},
		{
			Name = 'Exalted Blade',
			{'STR * 250', 'Damage', },
			{'DUR * 6', Unit = 's', 'Duration', },
			{'RNG * 5', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
			{'CHA * 2.5', Unit = '/s', 'Energy drain', },
		},
		{
			Name = 'Chromatic Blade',
			AUG = true,
		},
	},
	['FROST'] = {
		{
			Name = 'Freeze',
			{'STR * 350', 'Impact damage', },
			{'STR * 150', 'Area damage', },
			{'DUR * 15', Unit = 's', 'Freeze duration', },
			{'DUR * 12', Unit = 's', 'Ice duration', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Freeze Force',
			AUG = true,
			{'STR * 100', Unit = '%', 'Damage bonus', },
			{'DUR * 40', Unit = 's', 'Duration', },
			{'RNG * 15', Unit = 'm', 'Range', },
		},
		{
			Name = 'Ice Wave',
			{'STR * 700', 'Damage', },
			{'(50 * RNG), 60', Unit = '°', 'Angle', },
			{'RNG * 3', Unit = 'm', 'Initial width', },
			{'RNG * 20', Unit = 'm', 'Length', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Ice Wave Impedance',
			AUG = true,
			{'DUR * 12', Unit = 's', 'Duration', },
		},
		{
			Name = 'Snow Globe',
			{'(5000 + 5 * (300 * xARMOR + aARMOR)) * STR', 'Health', },
			{'STR * 150', 'Explosion Damage', },
			{'RNG * 5', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Chilling Globe',
			AUG = true,
			{'DUR * 8', Unit = 's', 'Duration', },
		},
		{
			Name = 'Avalanche',
			{'STR * 1500', 'Initial damage', },
			{'STR * 400', 'Explosion damage', },
			{'(STR * 40), 100', Unit = '%', 'Armor Reduction', },
			{'RNG * 15', Unit = 'm', 'Freeze range', },
			{'RNG * 4.5', Unit = 'm', 'Explosion range', },
			{'DUR * 8', Unit = 's', 'Duration', },
			{'(2 - EFF) * 100', 'Energy', },
		},
		{
			Name = 'Icy Avalanche',
			AUG = true,
		},
	},
	['GARA'] = {
		{
			Name = 'Shattered Lash',
			{'STR * 800', 'Damage', },
			{'RNG * 10', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Splinter Storm',
			{'STR * 250', 'Damage', },
			{'(STR * 70), 90', Unit = '%', 'Damage Reduction', },
			{'STR * 35', Unit = '%', 'Damage Multiplier', },
			{'DUR * 22', Unit = 's', 'Duration', },
			{'RNG * 30', Unit = 'm', 'Cast range', },
			{'RNG * 2.5', Unit = 'm', 'Ability range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Mending Splinters',
			AUG = true,
			{'STR * 3', Unit = '/s', 'Health regen', },
		},
		{
			Name = 'Spectrorage',
			{'STR * 800', 'Mirror damage', },
			{'STR * 1500', 'Collapse damage', },
			{'DUR * 22', Unit = 's', 'Duration', },
			{'RNG * 12', 'Mirrors', },
			{'RNG * 6', 'Collapse threshold', },
			{'RNG * 4', Unit = 'm', 'Charm radius', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Mass Vitrify',
		},
	},
	['GARUDA'] = {
		{
			Name = 'Dread Mirror',
			{'STR * 200', Unit = '%', 'Damage multiplier', },
			{'DUR * 20', Unit = 's', 'Duration', },
			{'RNG * 30', Unit = 'm', 'Pounce range', },
			{'RNG * 10', Unit = 'm', 'Explosion radius', },
			{'(2 - EFF) * 25', 'Energy', },
			{'CHA * 50', Unit = '/s', 'Energy drain', },
		},
		{
			Name = 'Dread Ward',
			AUG = true,
			{'DUR * 5', Unit = 's', 'Duration', },
		},
		{
			Name = 'Blood Altar',
			{'STR * 25', Unit = '%/s', 'Health regen', },
			{'DUR * 20', Unit = 's', 'Duration', },
			{'RNG * 30', Unit = 'm', 'Pounce range', },
			{'RNG * 8', Unit = 'm', 'Heal radius', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Bloodletting',
			{'25 / EFF', Unit = '%', 'Energy gain', },
		},
		{
			Name = 'Seeking Talons',
		},
	},
	['GAUSS'] = {
		{
			Name = 'Mach Rush',
			{'STR * 800', 'Damage', },
			{'RNG * 4', Unit = 'm', 'Knockdown range', },
			{'RNG * 10', Unit = 'm', 'Shockwave range', },
			{'(2 - EFF) * 15', 'Energy', },
		},
		{
			Name = 'Kinetic Plating',
			{'(STR * 20), 50', Unit = '% - ', 'Damage reduction', },
			{'DUR * 30', Unit = 's', 'Duration', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Thermal Sunder',
			{'STR * 150', Unit = ' - ', 'Cold/Heat damage', },
			{'STR * 300', Unit = ' - ', 'Blast damage', },
			{'DUR * 10', Unit = 's', 'Area duration', },
			{'DUR * 8', Unit = 's', 'Status duration', },
			{'RNG * 4', Unit = 'm - ', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Redline',
		},
	},
	['HARROW'] = {
		{
			Name = 'Condemn',
			{'STR * 150 * TARGET', 'Shields', },
			{'DUR * 6', Unit = 's', 'Duration', },
			{'RNG * 20', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Penance',
			{'STR * 5', Unit = '%', 'Lifesteal', },
			{'STR * 35', Unit = '%', 'Bonus fire rate', },
			{'STR * 70', Unit = '%', 'Bonus reload speed', },
			{'DUR * 6', Unit = 's', 'Base duration', },
			{'DUR * 1.54', Unit = 's', 'Duration every 100 shields', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Thurible',
			{'5 / (2 - EFF) * STR', Unit = '%', 'Conversion efficiency', },
			{'DUR * 35', Unit = 's', 'Duration', },
			{'RNG * 20', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Warding Thurible',
			AUG = true,
			{'(STR * 40), 90', Unit = '%', 'Damage reduction', },
			{'STR * 0.5', 'Energy per hit', },
		},
		{
			Name = 'Covenant',
			{'STR * 1.5', Unit = '%', 'critical chance every 100 damage', },
			{'DUR * 6', Unit = 's', 'Invulnerability duration', },
			{'DUR * 12', Unit = 's', 'Critical chance duration', },
			{'(2 - EFF) * 100', 'Energy', },
		},
		{
			Name = 'Lasting Covenant',
			AUG = true,
		},
	},
	['HILDRYN'] = {
		{
			Name = 'Balefire',
			{'STR * 500', 'Damage per bolt', },
			{'RNG * 3', Unit = 'm', 'Explosion radius', },
			{'(2 - EFF) * 50', 'Shields', },
			{'(2 - EFF) * 100', 'Shields per shot', },
		},
		{
			Name = 'Shield Pillage',
			{'(STR * 25), 100', Unit = '%', 'Shields/Armor reduction', },
			{'DUR * 2', Unit = 's', 'Duration', },
			{'RNG * 8', Unit = 'm', 'Final pulse radius', },
			{'(2 - EFF) * 25', 'Shields', },
		},
		{
			Name = 'Haven',
			{'STR * 500', 'Ally bonus shields', },
			{'STR * 200', Unit = '/s', 'Damage', },
			{'DUR * 80', Unit = '%', 'Recharge rate bonus', },
			{'(2 - EFF) * 250', 'Shields', },
			{'CHA * 5', Unit = '/s', 'Shields drain per ally', },
			{'CHA * 25', Unit = '/s', 'Shields drain per enemy', },
		},
		{
			Name = 'Aegis Storm',
		},
	},
	['HYDROID'] = {
		{
			Name = 'Tempest Barrage',
			{'STR * 150', Unit = ' - ', 'Damage', },
			{'DUR * 5', Unit = 's - ', 'Duration', },
			{'RNG * 5', Unit = 'm', 'Explosion range', },
			{'(2 - EFF) * 25', Unit = ' - ', 'Energy', },
		},
		{
			Name = 'Tidal Surge',
			{'STR * 300', 'Damage', },
			{'DUR * 30', Unit = 'm/s', 'Duration', },
			{'RNG * 6', Unit = 'm', 'Speed', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Tidal Impunity',
			AUG = true,
			{'DUR * 12', Unit = 's', 'Duration', },
		},
		{
			Name = 'Undertow',
			{'STR * 25', Unit = '/s', 'Damage', },
			{'STR * 2', Unit = '%/s', 'Damage increase', },
			{'Math.sqrt(RNG * 4)', Unit = 'm', 'Puddle size', },
			{'RNG * 15', Unit = 'm', 'Grab range', },
			{'(2 - EFF) * 15', 'Energy', },
			{'(2 - EFF) * 5', 'Energy/grab', },
			{'0.2 / EFF', Unit = 'm', 'Meters/Energy', },
			{'CHA * 2', 'Energy drain', },
		},
		{
			Name = 'Curative Undertow',
			AUG = true,
			{'(STR * 30), 100', Unit = '%', 'ally max health restored', },
			{'(STR * 10), 100', Unit = '%', 'self max health restored', },
		},
		{
			Name = 'Tentacle Swarm',
		},
	},
	['INAROS'] = {
		{
			Name = 'Desiccation',
			{'STR * 150', Unit = ' + ', 'Damage', },
			{'DUR * 8', Unit = 's', 'Duration', },
			{'RNG * 15', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Devour',
			{'STR * 125', Unit = '/s - ', 'Damage', },
			{'DUR * 30', Unit = 's', 'Duration', },
			{'RNG * 50', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Sandstorm',
			{'STR * 500', Unit = '/s', 'Damage', },
			{'RNG * 15', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
			{'CHA * 10', 'Energy drain', },
		},
		{
			Name = 'Elemental Sandstorm',
			AUG = true,
			{'(STR * 50), 100', Unit = '%', 'Status chance/sec', },
		},
		{
			Name = 'Scarab Swarm',
		},
	},
	['IVARA'] = {
		{
			Name = 'Quiver',
			{'DUR * 12', Unit = 's', 'Bubble duration', },
			{'DUR * 10', Unit = 's', 'Sleep duration', },
			{'RNG * 2.5', Unit = 'm', 'Bubble range', },
			{'RNG * 20', Unit = 'm', 'Noise range', },
			{'RNG * 6', Unit = 'm', 'Sleep range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Empowered Quiver',
			AUG = true,
			{'STR * 100', Unit = '%', 'Critical damage bonus', },
			{'(STR * 100), 100', Unit = '%', 'Chance to resist status', },
		},
		{
			Name = 'Navigator',
			{'STR * 5', Unit = 'x', 'Maximum damage multiplier', },
			{'1 / DUR', Unit = 'x/s', 'Multiplier growth', },
			{'(2 - EFF) * 25', 'Energy', },
			{'CHA * 3', Unit = '/s + ', 'Energy drain', },
		},
		{
			Name = 'Piercing Navigator',
			AUG = true,
			{'STR * 10', Unit = '%', 'Critical chance per hit', },
			{'STR * 50', Unit = '%', 'Maximum Critical chance', },
		},
		{
			Name = 'Prowl',
			{'STR * 40', Unit = '%', 'Bonus headshot damage', },
			{'(STR * 100), 100', Unit = '%', 'Loot chance', },
			{'2.5 / DUR', Unit = 's', 'Steal time', },
			{'RNG * 4', Unit = 'm', 'Steal range', },
			{'(2 - EFF) * 25', 'Energy', },
			{'CHA * 1', Unit = '/s - ', 'Energy drain', },
		},
		{
			Name = 'Infiltrate',
			AUG = true,
			{'STR * 25', Unit = '%', 'Movement speed bonus', },
		},
		{
			Name = 'Artemis Bow',
			{'STR * 160', 'Base damage', },
			{'(2 - EFF) * 50', 'Energy', },
			{'(2 - EFF) * 15', 'Energy/shot', },
		},
		{
			Name = 'Concentrated Arrow',
			AUG = true,
		},
	},
	['KHORA'] = {
		{
			Name = 'Whipclaw',
			{'STR * 300', 'Base damage', },
			{'RNG * 10', Unit = 'm', 'Cast range', },
			{'RNG * 5', Unit = 'm', 'Explosion range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Accumulating Whipclaw',
			AUG = true,
			{'(STR + 3.5) * 300', 'Maximum damage', },
		},
		{
			Name = 'Ensnare',
			{'DUR * 15', Unit = 's', 'Duration', },
			{'0.5 / DUR', Unit = 's', 'Spread delay', },
			{'RNG * 30', Unit = 'm', 'Cast range', },
			{'RNG * 10', Unit = 'm', 'Spread range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Venari',
			{'1 + STR * 0.15', Unit = '%', 'Speed multiplier', },
			{'STR * 350', 'Snare damage', },
			{'STR * 50', Unit = '/s', 'Health regen', },
			{'(2 - EFF) * 25', 'Command energy', },
			{'(2 - EFF) * 50', 'Revive energy', },
		},
		{
			Name = 'Strangledome',
		},
	},
	['LIMBO'] = {
		{
			Name = 'Banish',
			{'STR * 250', 'Damage', },
			{'DUR * 25', Unit = 's', 'Duration', },
			{'RNG * 35', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Rift Haven',
			AUG = true,
			{'(STR * 25), 100', Unit = '%', 'Health restored', },
		},
		{
			Name = 'Stasis',
			{'DUR * 15', Unit = 's', 'Duration', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Rift Surge',
			{'DUR * 25', Unit = 's', 'Surge duration', },
			{'DUR * 18', Unit = 's', 'Banish duration', },
			{'RNG * 25', Unit = 'm', 'Surge/transfer radius', },
			{'RNG * 5', Unit = 'm', 'Banish radius', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Rift Torrent',
			AUG = true,
			{'STR * 30 * TARGET', Unit = '%', 'Damage bonus while rifted', },
		},
		{
			Name = 'Cataclysm',
		},
	},
	['LOKI'] = {
		{
			Name = 'Decoy',
			{'DUR * 25', Unit = 's', 'Duration', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Invisibility',
			{'DUR * 12', Unit = 's', 'Duration', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Switch Teleport',
			{'RNG * 75', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Safeguard Switch',
			AUG = true,
			{'DUR * 6', Unit = 's', 'Range', },
		},
		{
			Name = 'Radial Disarm',
		},
	},
	['MAG'] = {
		{
			Name = 'Pull',
			{'STR * 300', 'Damage', },
			{'STR * 25, 100', Unit = '%', 'Energy drop chance', },
			{'RNG * 25', Unit = 's', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Magnetize',
			{'STR * 2', Unit = '%', 'Multiplier', },
			{'STR * 300', 'Explosion damage', },
			{'DUR * 15', Unit = 's', 'Duration', },
			{'RNG * 4', Unit = 'm', 'Field radius', },
			{'RNG * 15', Unit = 'm', 'Explosion radius', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Magnetized Discharge',
			AUG = true,
			{'STR * 50, 100', Unit = '%', 'Disarm chance', },
		},
		{
			Name = 'Polarize',
			{'STR * 400', 'Damage', },
			{'STR * 2.5', Unit = 'x', 'Damage multiplier', },
			{'DUR * 5', Unit = 's', 'Duration', },
			{'RNG * 8', Unit = 'm', 'Initial/explosion radius', },
			{'RNG * 8 + DUR * 5 * 5.9', Unit = 'm', 'Maximum pulse range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Counter Pulse',
			AUG = true,
			{'DUR * 4', Unit = 's', 'Disable/jamming duration', },
		},
		{
			Name = 'Crush',
			{'STR * 1500', 'Damage', },
			{'STR * 25 * TARGET', 'Shields restored', },
			{'RNG * 18', Unit = 'm', 'Range', },
			{'(2 - EFF) * 100', 'Energy', },
		},
		{
			Name = 'Fracturing Crush',
			AUG = true,
		},
	},
	['MESA'] = {
		{
			Name = 'Ballistic Battery',
			{'STR * 30', Unit = '%', 'Damage conversion', },
			{'STR * 140', 'Max damage per instance', },
			{'STR * 1600', 'Max stored damage', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Shooting Gallery',
			{'STR * 25', Unit = '%', 'Damage bonus', },
			{'DUR * 30', Unit = 's', 'Duration', },
			{'RNG * 16', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Muzzle Flash',
			AUG = true,
			{'RNG * 8', Unit = 'm', 'Blind range', },
			{'DUR * 7', Unit = 's', 'Blind duration', },
		},
		{
			Name = 'Shatter Shield',
			{'STR * 80, 95', Unit = '%', 'Damage reduction', },
			{'DUR * 25', Unit = 's', 'Duration', },
			{'RNG * 11', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Peacemaker',
		},
	},
	['MIRAGE'] = {
		{
			Name = 'Hall Of Mirrors',
			{'STR * 20', Unit = '%', 'Damage', },
			{'DUR * 25', Unit = 's', 'Duration', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Sleight Of Hand',
			{'STR * 200', 'Pickup/Jewel explosion damage', },
			{'DUR * 18', Unit = 's', 'Trap duration', },
			{'DUR * 5', Unit = 's', 'Blind duration', },
			{'RNG * 40', Unit = 'm', 'Trap radius', },
			{'RNG * 12', Unit = 'm', 'Jewel charm radius', },
			{'RNG * 8', Unit = 'm', 'Explosion/blind radius', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Explosive Legerdemain',
			AUG = true,
			{'STR * 500', 'Mine damage', },
		},
		{
			Name = 'Eclipse',
			{'STR * 200', Unit = '%', 'Maximum damage bonus', },
			{'STR * 75, 95', Unit = '%', 'Maximum damage reduction', },
			{'DUR * 25', Unit = 's', 'Duration', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Total Eclipse',
			AUG = true,
			{'RNG * 15', Unit = 'm', 'Range', },
		},
		{
			Name = 'Prism',
		},
	},
	['NEKROS'] = {
		{
			Name = 'Soul Punch',
			{'STR * 500', 'Initial damage', },
			{'RNG * 50', Unit = 'm', 'Cast range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Soul Survivor',
			AUG = true,
			{'STR * 30, 100', Unit = '%', 'Health restored', },
		},
		{
			Name = 'Terrify',
			{'STR * 20', 'Affected enemies', },
			{'STR * 20, 100', Unit = '%', 'Armor reduction', },
			{'DUR * 25', Unit = 's', 'Duration', },
			{'RNG * 15', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Creeping Terrify',
			AUG = true,
			{'STR * 60, 80', Unit = '%', 'Movement speed reduction', },
		},
		{
			Name = 'Desecrate',
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 10', 'Energy/energy per corpse', },
		},
		{
			Name = 'Despoil',
			AUG = true,
			{'(2 - EFF) * 10', 'Health per corpse', },
		},
		{
			Name = 'Shadows Of The Dead',
			{'STR * 150', Unit = '%', 'Damage bonus', },
			{'STR * 100', Unit = '%', 'Shield/health bonus', },
			{'3 / DUR', Unit = '%/s', 'Health decay', },
			{'(2 - EFF) * 100', 'Energy', },
		},
		{
			Name = 'Shield Of Shadows',
			AUG = true,
		},
	},
	['NEZHA'] = {
		{
			Name = 'Fire Walker',
			{'STR * 200', Unit = '/s', 'Damage', },
			{'STR * 1250', 'Explosion damage', },
			{'DUR * 30', Unit = 's', 'Ability duration', },
			{'DUR * 10', Unit = 's', 'Flame duration', },
			{'RNG * 6', Unit = 'm', 'Explosion radius', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Pyroclastic Flow',
			AUG = true,
			{'DUR * 10', Unit = 's', 'Trail duration', },
		},
		{
			Name = 'Blazing Chakram',
			{'STR * 250', 'Damage', },
			{'STR * 1000', 'Boosted damage', },
			{'STR * 100', Unit = '%', 'Damage multiplier', },
			{'DUR * 15', Unit = 's', 'Duration', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Warding Halo',
			{'(1000 + 2.5 * (190 * (1 + xARMOR) + aARMOR)) * STR', 'Base health', },
			{'STR * 125', Unit = '/s', 'Damage', },
			{'STR * 2.5', Unit = '%', 'Absorption multiplier', },
			{'RNG * 2', Unit = 's', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Divine Spears',
		},
	},
	['NIDUS'] = {
		{
			Name = 'Virulence',
			{'STR * 200 * (1 + STACK)', 'Damage', },
			{'RNG * 16', Unit = 'm', 'Range', },
			{'(2 - EFF) * 40', 'Energy', },
		},
		{
			Name = 'Teeming Virulence',
			AUG = true,
			{'STR * 120', Unit = '%', 'Critical chance bonus', },
			{'DUR * 15', Unit = 's', 'Duration', },
		},
		{
			Name = 'Larva',
			{'DUR * 7', Unit = 's', 'Duration', },
			{'RNG * 12', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Larva Burst',
			AUG = true,
			{'STR * 300', 'Damage', },
			{'RNG * 5', Unit = 'm', 'Range', },
		},
		{
			Name = 'Parasitic Link',
			{'STR * 25', Unit = '%', 'Ability Strength multiplier', },
			{'STR * 50, 90', Unit = '%', 'Damage redirection', },
			{'DUR * 60', Unit = 's', 'Duration', },
			{'RNG * 40', Unit = 'm', 'Ally link', },
			{'RNG * 20', Unit = 'm', 'Enemy link', },
		},
		{
			Name = 'Ravenous',
		},
	},
	['NOVA'] = {
		{
			Name = 'Null Star',
			{'STR * 200', 'Damage', },
			{'DUR * 6', 'Particles', },
			{'(Math.round(DUR * 6) * 5), 100', Unit = '%', 'Maximum damage reduction', },
			{'RNG * 12', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Neutron Star',
			AUG = true,
			{'STR * 120', 'Damage per particle', },
			{'Math.round(DUR * 6) * STR * 120', 'Maximum damage', },
			{'RNG * 8', Unit = 'm', 'explosion range', },
		},
		{
			Name = 'Antimatter Drop',
			{'STR * 200', 'Base damage', },
			{'STR * 10', 'Contact damage', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Antimatter Absorb',
			AUG = true,
			{'RNG * 3', Unit = 'm', 'Absorb radius', },
		},
		{
			Name = 'Worm Hole',
			{'DUR * 16', Unit = 's', 'Duration', },
			{'RNG * 50', Unit = 'm', 'Energy', },
			{'(2 - EFF) * 75', },
		},
		{
			Name = 'Escape Velocity',
			AUG = true,
			{'DUR * 7', Unit = 's', 'Duration', },
		},
		{
			Name = 'Molecular Prime',
		},
	},
	['NYX'] = {
		{
			Name = 'Mind Control',
			{'DUR * 30', Unit = 's', 'Duration', },
			{'RNG * 60', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Mind Freak',
			AUG = true,
			{'STR * 500', Unit = '%', 'Damage bonus', },
		},
		{
			Name = 'Psychic Bolts',
			{'(STR * 80), 100', Unit = '%', 'Debuff', },
			{'DUR * 11', Unit = 's', 'Duration', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Pacifying Bolts',
			AUG = true,
			{'DUR * 10', Unit = 's', 'Duration', },
		},
		{
			Name = 'Chaos',
			{'DUR * 25', Unit = 's', 'Duration', },
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Absorb',
		},
	},
	['OBERON'] = {
		{
			Name = 'Smite',
			{'STR * 500', 'Initial damage', },
			{'STR * 150', 'Orb base damage', },
			{'STR * 6', 'Number of orbs', },
			{'DUR * 12', Unit = 's', 'Duration', },
			{'RNG * 50', Unit = 'm', 'Cast range', },
			{'RNG * 12.5', Unit = 'm', 'Orb range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Smite Infusion',
			AUG = true,
			{'STR * 100', Unit = '%', 'Damage bonus', },
			{'DUR * 40', Unit = 's', 'Duration', },
			{'RNG * 15', Unit = 'm', 'Range', },
		},
		{
			Name = 'Hallowed Ground',
			{'STR * 100', Unit = '/s', 'Damage', },
			{'(STR * 15), 100', Unit = '%', 'Status chance', },
			{'DUR * 20', Unit = 's', 'Duration', },
			{'Math.min(180 + 135 * (RNG - 1), 360)', Unit = '°', 'Angle', },
			{'15 + 11.25 * (RNG - 1)', Unit = 'm', 'Radius', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Hallowed Eruption',
			AUG = true,
			{'DUR * 40', Unit = 's', 'Duration', },
			{'STR * 100 * DUR * 40', 'Maximum damage', },
		},
		{
			Name = 'Renewal',
			{'4 / STR', Unit = 's', 'Wave duration', },
			{'STR * 200', 'Armor buff', },
			{'STR * 125', 'Initial heal', },
			{'STR * 40', Unit = '/s', 'Health regen', },
			{'DUR * 45', Unit = '%', 'Bleedout slow', },
			{'DUR * 20', Unit = 's', 'Duration', },
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
			{'CHA * (2 + 3 * TARGET)', Unit = '/s', 'Energy drain', },
		},
		{
			Name = 'Phoenix Renewal',
			AUG = true,
			{'(STR * 50), 100', Unit = '%', 'Health restored', },
		},
		{
			Name = 'Reckoning',
			{'(STR * 30), 100', Unit = '%', 'Armor reduction', },
			{'STR * 1250', 'Damage', },
			{'STR * 625', 'Extra damage', },
			{'DUR * 4', Unit = 's', 'Duration', },
			{'RNG * 4', Unit = 'm', 'Blind range', },
			{'RNG * 15', Unit = 'm', 'Cast range', },
			{'(2 - EFF) * 100', 'Energy', },
		},
		{
			Name = 'Hallowed Reckoning',
			AUG = true,
		},
	},
	['OCTAVIA'] = {
		{
			Name = 'Mallet',
			{'STR * 2.5', Unit = '%', 'Damage multiplier', },
			{'DUR * 20', Unit = 's', 'Duration', },
			{'RNG * 10', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Resonator',
			{'STR * 125', 'Damage', },
			{'DUR * 20', Unit = 's', 'Duration', },
			{'RNG * 6', Unit = 'm - ', 'Charm radius', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Metronome',
			{'STR * 35', Unit = '%', 'Armor bonus', },
			{'STR * 30', Unit = '%', 'Speed/multishot/melee damage bonus', },
			{'DUR * 20', Unit = 's', 'Ability duration', },
			{'DUR * 15', Unit = 's', 'Buff duration', },
			{'RNG * 12', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Amp',
		},
	},
	['REVENANT'] = {
		{
			Name = 'Enthrall',
			{'STR * 1000', Unit = '/s', 'Damage', },
			{'DUR * 30', Unit = 's', 'Thrall duration', },
			{'DUR * 10', Unit = 's', 'Pillar duration', },
			{'RNG * 25', Unit = 'm', 'Cast range', },
			{'RNG * 2', Unit = 'm', 'Effect range', },
			{'(2 - EFF) * 25', 'Projectile range', },
		},
		{
			Name = 'Mesmer Skin',
			{'DUR * 5', Unit = 's', 'Charges', },
			{'(2 - EFF) * 50', 'stun duration', },
		},
		{
			Name = 'Reave',
			{'(STR * 8), 100', Unit = '%', 'Hitpoints drain/restore', },
			{'(STR * 40), 100', Unit = '%', 'Thrall hitpoints drain/restore', },
			{'DUR', Unit = 's', 'Duration', },
			{'RNG * 6', Unit = 's', 'Width', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Blinding Reave',
			AUG = true,
			{'DUR * 10', Unit = 's', 'Duration', },
		},
		{
			Name = 'Danse Macabre',
		},
	},
	['RHINO'] = {
		{
			Name = 'Rhino Charge',
			{'STR * 650 * COMBO', 'Damage', },
			{'DUR', Unit = 's', 'Combo Window', },
			{'RNG * 12 * (1 + 0.25 * Math.min(COMBO - 1, 2))', Unit = 'm', 'Charge radius', },
			{'RNG * 2', Unit = 'm', 'Impact radius', },
			{'(2 - EFF) * 25 / COMBO', 'Energy', },
		},
		{
			Name = 'Ironclad Charge',
			AUG = true,
			{'STR * 50 * TARGET', Unit = '%', 'Armor bonus', },
			{'DUR * 10', Unit = 's', 'Duration', },
		},
		{
			Name = 'Iron Skin',
			{'(1200 + (2.5 * ((190 + aARMOR) * (1 + xARMOR)) * (1 + existance(IRONCLAD_CHARGE)))) * STR', 'Base health', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Iron Shrapnel',
			AUG = true,
			{'RNG * 8', Unit = 'm', 'Range', },
		},
		{
			Name = 'Roar',
			{'STR * 50', Unit = '%', 'Bonus damage', },
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Piercing Roar',
			AUG = true,
			{'STR * 150', 'Damage', },
			{'DUR * 6', Unit = 's', 'Duration', },
			{'RNG * 25', Unit = 'm', 'Range', },
		},
		{
			Name = 'Rhino Stomp',
			{'STR * 800', 'Damage', },
			{'DUR * 8', Unit = 's', 'Duration', },
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 100', 'Energy', },
		},
		{
			Name = 'Reinforcing Stomp',
			AUG = true,
		},
	},
	['SARYN'] = {
		{
			Name = 'Spores',
			{'STR * 10', 'Damage', },
			{'STR * 2', 'Damage growth per enemy', },
			{'(STR * 50), 100', Unit = '%', 'Status chance', },
			{'20 / STR', Unit = '%', 'Reset decay', },
			{'10 / DUR', Unit = '%', 'Damage decay rate', },
			{'RNG * 60', Unit = 'm', 'Cast range', },
			{'RNG * 16', Unit = 'm', 'Spread range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Venom Dose',
			AUG = true,
			{'STR * 100', Unit = '%', 'Damage bonus', },
			{'DUR * 40', Unit = 's', 'Duration', },
			{'RNG * 15', Unit = 'm', 'Range', },
		},
		{
			Name = 'Molt',
			{'STR * 500', 'Health', },
			{'STR * 400', 'Explosion damage', },
			{'STR * 1.5', Unit = 'x', 'Speed multiplier', },
			{'DUR * 10', Unit = 's', 'Decoy duration', },
			{'DUR * 5', Unit = 's', 'Speed duration', },
			{'RNG * 10', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Regenerative Molt',
			AUG = true,
			{'STR * 50', Unit = '/s', 'Health regen', },
		},
		{
			Name = 'Toxic Lash',
			{'STR * 30', Unit = '%', 'Bonus gun damage', },
			{'STR * 60', Unit = '%', 'Bonus melee damage', },
			{'(STR * 40), 90', Unit = '%', 'Damage block', },
			{'DUR * 45', Unit = 's', 'Duration', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Contagion Cloud',
			AUG = true,
			{'STR * 300', Unit = ' - ', 'Damage', },
			{'DUR * 12', Unit = 's', 'Duration', },
			{'RNG * 5', Unit = 'm', 'Range', },
		},
		{
			Name = 'Miasma',
		},
	},
	['TITANIA'] = {
		{
			Name = 'Spellbind',
			{'DUR * 16', Unit = 's', 'Duration', },
			{'RNG * 5', Unit = 'm', 'Ability range', },
			{'RNG * 50', Unit = 'm', 'Cast range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Tribute',
			{'STR * 500', 'Damage', },
			{'DUR * 12', Unit = 's', 'Duration', },
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Lantern',
			{'STR * 350', Unit = '/s', 'Damage', },
			{'STR * 2500', 'Explosion damage', },
			{'DUR * 25', Unit = 's', 'Duration', },
			{'RNG * 25', Unit = 'm', 'Cast range', },
			{'RNG * 20', Unit = 'm', 'Attract range', },
			{'RNG * 8', Unit = 'm', 'Blast range', },
			{'RNG * 2.5', Unit = 'm', 'DoT range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Beguiling Lantern',
			AUG = true,
			{'STR * 100', Unit = '%', 'Bonus melee damage', },
		},
		{
			Name = 'Razorwing',
			{'STR * 160', 'Gun damage', },
			{'STR * 200', 'Melee damage', },
			{'STR * 80', 'Drone damage', },
			{'(2 - EFF) * 25', 'Energy', },
			{'CHA * 5', Unit = '/s', 'Energy drain', },
		},
		{
			Name = 'Razorwing Blitz',
			AUG = true,
		},
	},
	['TRINITY'] = {
		{
			Name = 'Well Of Life',
			{'STR * 45', Unit = '%', 'Lifesteal', },
			{'STR * 400', 'Max health', },
			{'DUR * 12', Unit = 's', 'Duration', },
			{'RNG * 100', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Pool Of Life',
			AUG = true,
			{'STR * 25', Unit = '%', 'Energy orb chance', },
		},
		{
			Name = 'Energy Vampire',
			{'STR * 25', 'Restored energy', },
			{'STR * 6.25', Unit = '%', 'Damage', },
			{'DUR * 9', Unit = 's', 'Duration', },
			{'RNG * 100', Unit = 'm', 'Cast range', },
			{'RNG * 25', Unit = 'm', 'Pulse range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Link',
			{'DUR * 12', Unit = 's', 'Duration', },
			{'RNG * 20', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Abating Link',
			AUG = true,
			{'(STR * 45), 100', Unit = '%', 'Armor reduction', },
		},
		{
			Name = 'Blessing',
		},
	},
	['VALKYR'] = {
		{
			Name = 'Rip Line',
			{'STR * 500 * COMBO', 'Damage', },
			{'DUR', Unit = 's', 'Duration', },
			{'RNG * 75', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25 * (1 / COMBO)', 'Energy', },
		},
		{
			Name = 'Warcry',
			{'STR * 50', Unit = '%', 'Attack speed/Armor buff', },
			{'(STR * 30), 75', Unit = '%', 'Movement speed reduction', },
			{'DUR * 15', Unit = 's', 'Duration', },
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Eternal War',
			AUG = true,
			{'DUR * 2', Unit = 's', 'Duration per kill', },
		},
		{
			Name = 'Paralysis',
			{'STR * 3.5', Unit = 'x', 'Damage multiplier', },
			{'STR * 1000', 'knockback strength', },
			{'RNG * 10', Unit = 'm', 'Range', },
			{'(2 - EFF) * 5', 'Energy', },
		},
		{
			Name = 'Prolonged Paralysis',
			AUG = true,
			{'STR * 200', Unit = '%', 'Stun duration', },
		},
		{
			Name = 'Hysteria',
			{'STR * 250', 'Damage', },
			{'(2 - EFF) * 25', 'Energy', },
			{'CHA * 2.5', Unit = '/s - ', 'Energy drain', },
		},
		{
			Name = 'Hysterical Assault',
			AUG = true,
		},
	},
	['VAUBAN'] = {
        Types = {"Minelayer", "Tether Coil", "Flechette Orb", "Vector Pad", "Overdriver"},
        {
            Name = 'Tesla Nervos',
        },
        {
            Name = 'Tesla Bank',
            AUG = true,
        },
        {
            Name = 'Minelayer',
            Type = 'Tether Coil',
            {'15*STR', 'Blast Damage'},
            {'250*STR', 'Slash Damage'},
            {'25*DUR', Unit = "s", 'Duration'},
            {'20*RNG', Unit = "m", 'Grab Range'},
            {'25*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Minelayer',
            Type = 'Flechette Orb',
            {'15*STR', 'Blast Damage'},
            {'300*STR', 'Puncture Damage per Nail'},
            {'25*DUR', Unit = "s", 'Duration'},
            {'25*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Minelayer',
            Type = 'Vector Pad',
            {'15*STR', 'Blast Damage'},
            {'25*STR', Unit = "m/s", 'Speed Boost'},
            {'25*DUR', Unit = "s", 'Duration'},
            {'25*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Minelayer',
            Type = 'Overdriver',
            {'15*STR', 'Blast Damage'},
            {'25*STR', Unit = "%", 'Damage Bonus'},
            {'25*DUR', Unit = "s", 'Duration'},
            {'10*RNG', Unit = "m", 'Attach Range'},
            {'25*(2 - EFF)', 'Energy'},
        },
        {
            Name = 'Photon Strike',
        },
        {
            Name = 'Photon Repeater',
            AUG = true,
        },
        {
            Name = 'Bastille',
        },
        {
            Name = 'Repelling Bastille',
            AUG = true,
        },
    },
	['VOLT'] = {
		{
			Name = 'Shock',
			{'STR * 200', 'Damage', },
			{'RNG * 15', Unit = 'm', 'Chain range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Shock Trooper',
			AUG = true,
			{'STR * 100', Unit = '%', 'Damage bonus', },
			{'DUR * 40', Unit = 's', 'Duration', },
			{'RNG * 15', Unit = 'm', 'Range', },
		},
		{
			Name = 'Speed',
			{'STR * 50', Unit = '%', 'Attack/movement Speed buff', },
			{'STR * 17', Unit = '%', 'Reload speed buff', },
			{'DUR * 10', Unit = 's', 'Duration', },
			{'RNG * 25', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Shocking Speed',
			AUG = true,
			{'STR * 175', 'Damage', },
		},
		{
			Name = 'Electric Shield',
			{'DUR * 25', Unit = 's', 'Duration', },
			{'(2 - EFF) * 50', 'Energy', },
			{'4 / EFF', Unit = 'm', 'Meters per energy', },
		},
		{
			Name = 'Transistor Shield',
			AUG = true,
			{'STR * 300', Unit = '%', 'Damage conversion', },
		},
		{
			Name = 'Discharge',
		},
	},
	['WISP'] = {
		{
			Name = 'Reservoirs',
			{'STR * 300', 'Max health', },
			{'STR * 30', Unit = '/s', 'Health regen', },
			{'STR * 20', Unit = '%', 'Bonus movement speed', },
			{'STR * 30', Unit = '%', 'Bonus attack speed', },
			{'STR * 5', 'Shock damage', },
			{'RNG * 5', Unit = 'm', 'Reservoir range', },
			{'RNG * 15', Unit = 'm', 'Shock range', },
			{'DUR * 30', Unit = 's', 'Mote lifespan', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Wil O Wisp',
			{'DUR * 4', Unit = 's', 'Duration', },
			{'(2 - EFF) * 35', 'Energy', },
		},
		{
			Name = 'Breach Surge',
			{'STR * 2', Unit = 'x', 'Damage multiplier', },
			{'(STR * 20), 100', Unit = '/s', 'Status chance', },
			{'DUR * 16', Unit = 's', 'Blind duration', },
			{'RNG * 15', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Sol Gate',
		},
	},
	['WUKONG'] = {
		{
			Name = 'Celestial Twin',
			{'STR * 2', Unit = 'x', 'Health multiplier', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Celestial Stomp',
			AUG = true,
			{'RNG * 20', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Cloud Walker',
			{'STR * 1', Unit = '%/m', 'Health regen', },
			{'DUR * 2', Unit = 's', 'Duration', },
			{'RNG * 8', Unit = 'm', 'Range', },
			{'(2 - EFF) * 25', 'Energy', },
		},
		{
			Name = 'Enveloping Cloud',
			AUG = true,
			{'RNG * 4', Unit = 'm', 'Duration', },
			{'DUR * 14', Unit = 's', 'Range', },
		},
		{
			Name = 'Defy',
			{'STR * 7.5', Unit = 'x', 'Damage multiplier', },
			{'STR * 1.5', Unit = 'x', 'Armor multiplier', },
			{'DUR * 2', Unit = 's', 'Invulnerability duration', },
			{'DUR * 25', Unit = 's', 'Armor duration', },
			{'RNG * 12', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', 'Energy', },
		},
		{
			Name = 'Primal Fury',
			{'STR * 250', 'Damage', },
			{'(2 - EFF) * 10', 'Energy', },
			{'CHA * 5', Unit = '/s', 'Energy drain', },
		},
		{
			Name = 'Primal Rage',
			AUG = true,
		},
	},
	['ZEPHYR'] = {
		{
			Name = 'Tail Wind',
			{'STR * 500', 'Damage', },
			{'DUR * 30', Unit = 's', 'Speed', },
			{'DUR * 12.5', Unit = 'm', 'Hover height', },
			{'RNG * 2', Unit = 'm', 'Contact range', },
			{'RNG * 7', Unit = 'm', 'Explosion range', },
			{'(2 - EFF) * 25', Unit = ' - ', 'Energy', },
		},
		{
			Name = 'Airburst',
			{'STR * 500', 'Contact/explosion damage', },
			{'RNG * 8', Unit = 'm', 'Range', },
			{'(2 - EFF) * 50', Unit = ' - ', 'Energy', },
		},
		{
			Name = 'Turbulence',
			{'DUR * 20', Unit = 's', 'Duration', },
			{'RNG * 6', Unit = 'm', 'Range', },
			{'(2 - EFF) * 75', 'Energy', },
		},
		{
			Name = 'Jet Stream',
			AUG = true,
			{'STR * 40', Unit = '%', 'Movement speed bonus', },
			{'STR * 100', Unit = '%', 'Projectile speed bonus', },
		},
		{
			Name = 'Tornado',
		},
	},
}

return Data;