-- Last Updated 2/23/21

local WarframeData = {
    ["IgnoreInCount"] = {"Excalibur Umbra Prime"},
    ["Warframes"] = {
        ["Ash"] = {
            Armor = 100,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 150,
            Image = "AshNewLook.png",
            Portrait = "AshIcon272.png",
            Name = "Ash",
            Polarities = {"V", "V"},
            Shield = 100,
            Sprint = 1.15,
            Subsumed = "Shuriken",
            Introduced = "Vanilla",
            Themes = "Assassin, Ninja",
            Sex = "Male",
            MainCost = {
                Credits = 25000,
                BPCost = 35000,
                MarketCost = 375,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Alloy Plate",Type = "Resource",Count = 150,},
                    { Name = "Neural Sensors",Type = "Resource",Count = 1,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 150,},
                    { Name = "Rubedo",Type = "Resource",Count = 500,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Morphics",Type = "Resource",Count = 1,},
                    { Name = "Ferrite",Type = "Resource",Count = 1000,},
                    { Name = "Rubedo",Type = "Resource",Count = 300,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Control Module",Type = "Resource",Count = 1,},
                    { Name = "Morphics",Type = "Resource",Count = 1,},
                    { Name = "Salvage",Type = "Resource",Count = 500,},
                    { Name = "Plastids",Type = "Resource",Count = 500,},},
            },
        },
        ["Ash Prime"] = {
            Armor = 175,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 150,
            Image = "AshPrimeNewLook.png",
            Portrait = "Ash PrimeIcon272.png",
            Name = "Ash Prime",
            Polarities = {"Bar", "V", "V"},
            Shield = 125,
            Sprint = 1.2,
            Subsumed = "Shuriken",
            Introduced = "16.11",
            Themes = "Assassin, Ninja",
            Sex = "Male",
            Vaulted = true,
            MainCost = {
                Credits = 25000,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Prime Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Prime Chassis",Type = "Item",Count = 1,},
                    { Name = "Prime Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Alloy Plate",Type = "Resource",Count = 150,},
                    { Name = "Neural Sensors",Type = "Resource",Count = 2,},
                    { Name = "Salvage",Type = "Resource",Count = 1000,},
                    { Name = "Rubedo",Type = "Resource",Count = 750,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Gallium",Type = "Resource",Count = 3,},
                    { Name = "Nano Spores",Type = "Resource",Count = 1000,},
                    { Name = "Rubedo",Type = "Resource",Count = 400,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Control Module",Type = "Resource",Count = 3,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},
                    { Name = "Ferrite",Type = "Resource",Count = 1000,},
                    { Name = "Circuits",Type = "Resource",Count = 500,},},
            },
        },
        ["Atlas"] = {
            Armor = 450,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "AtlasNewLook.png",
            Portrait = "AtlasIcon272.png",
            Name = "Atlas",
            Polarities = {"Bar", "D", "V"},
            Shield = 100,
            Sprint = 0.9,
            Subsumed = "Petrify",
            Introduced = "17.5",
            Themes = "Brawler, Earth Elemental",
            Sex = "Male",
            MainCost = {
                Credits = 30000,
                MarketCost = 275,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Polymer Bundle",Type = "Resource",Count = 1400,},
                    { Name = "Alloy Plate",Type = "Resource",Count = 1100,},
                    { Name = "Circuits",Type = "Resource",Count = 800,},
                    { Name = "Neurodes",Type = "Resource",Count = 5,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Nano Spores",Type = "Resource",Count = 1800,},
                    { Name = "Cryotic",Type = "Resource",Count = 1300,},
                    { Name = "Rubedo",Type = "Resource",Count = 700,},
                    { Name = "Argon Crystal",Type = "Resource",Count = 2},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Ferrite",Type = "Resource",Count = 4600,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 1700,},
                    { Name = "Morphics",Type = "Resource",Count = 5,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
        },
        ["Atlas Prime"] = {
            Armor = 475,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 175,
            Health = 175,
            Image = "AtlasPrime.png",
            Portrait = "Atlas_PrimeIcon272.png",
            --Mastery = ,
            Name = "Atlas Prime",
            Polarities = {"Bar", "D", "V", "V"},
            Shield = 150,
            Sprint = 1.0,
            Subsumed = "Petrify",
            Introduced = "25.8",
            Themes = "Brawler, Earth Elemental",
            Sex = "Male",
            Vaulted = false,
            MainCost = {
                Credits = 25000,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Prime Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Prime Chassis",Type = "Item",Count = 1,},
                    { Name = "Prime Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 5,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 50,
                Time = 12,
                Parts = {
                    { Name = "Neural Sensors",Type = "Resource",Count = 2,},
                    { Name = "Cryotic",Type = "Resource",Count = 525,},
                    { Name = "Salvage",Type = "Resource",Count = 4700,},
                    { Name = "Oxium",Type = "Resource",Count = 200,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 50,
                Time = 12,
                Parts = {
                    { Name = "Tellurium",Type = "Resource",Count = 2,},
                    { Name = "Nitain Extract",Type = "Resource",Count = 2,},
                    { Name = "Rubedo",Type = "Resource",Count = 725,},
                    { Name = "Ferrite",Type = "Resource",Count = 3600,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Argon Crystal",Type = "Resource",Count = 2,},
                    { Name = "Gallium",Type = "Resource",Count = 4,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 1200,},
                    { Name = "Alloy Plate",Type = "Resource",Count = 3200,},},
            },
        },
        ["Banshee"] = {
            Armor = 100,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "BansheeNewLook.png",
            Portrait = "BansheeIcon272.png",
            Name = "Banshee",
            Polarities = {"V", "V"},
            Shield = 100,
            Sprint = 1.1,
            Subsumed = "Silence",
            Introduced = "7",
            Themes = "Sound, Wailing Spirit",
            Sex = "Female",
            MainCost = {
                Credits = 25000,
                MarketCost = 225,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Circuits",Type = "Resource",Count = 150,},
                    { Name = "Neural Sensors",Type = "Resource",Count = 1,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 200,},
                    { Name = "Salvage",Type = "Resource",Count = 500,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Morphics",Type = "Resource",Count = 1,},
                    { Name = "Ferrite",Type = "Resource",Count = 900,},
                    { Name = "Rubedo",Type = "Resource",Count = 50,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Control Module",Type = "Resource",Count = 1,},
                    { Name = "Morphics",Type = "Resource",Count = 1,},
                    { Name = "Salvage",Type = "Resource",Count = 500,},
                    { Name = "Plastids",Type = "Resource",Count = 400,},},
            },
        },
        ["Banshee Prime"] = {
            Armor = 125,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 175,
            Health = 100,
            Image = "BansheePrimeIcon.png",
            Portrait = "Banshee PrimeIcon272.png",
            Mastery = 8,
            Name = "Banshee Prime",
            Polarities = {"V", "V", "Bar"},
            Shield = 100,
            Sprint = 1.15,
            Subsumed = "Silence",
            Introduced = "19.11.5",
            Themes = "Sound, Wailing Spirit",
            Sex = "Female",
            Vaulted = true,
            MainCost = {
                Credits = 25000,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Prime Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Prime Chassis",Type = "Item",Count = 1,},
                    { Name = "Prime Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 5,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Neural Sensors",Type = "Resource",Count = 2,},
                    { Name = "Alloy Plate",Type = "Resource",Count = 6000,},
                    { Name = "Circuits",Type = "Resource",Count = 1500,},
                    { Name = "Nitain Extract",Type = "Resource",Count = 2,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Morphics",Type = "Resource",Count = 10,},
                    { Name = "Cryotic",Type = "Resource",Count = 1500,},
                    { Name = "Rubedo",Type = "Resource",Count = 2000,},
                    { Name = "Salvage",Type = "Resource",Count = 7000,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Argon Crystal",Type = "Resource",Count = 2,},
                    { Name = "Control Module",Type = "Resource",Count = 10,},
                    { Name = "Oxium",Type = "Resource",Count = 300,},
                    { Name = "Ferrite",Type = "Resource",Count = 4500,},},
            },
        },
        ["Baruuk"] = {
            Armor = 175,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 200,
            ExilusPolarity = "Bar",
            Health = 75,
            Image = "BaruukIcon272.png",
            Portrait = "BaruukIcon272.png",
            Name = "Baruuk",
            Polarities = {"D", "D"},
            Shield = 100,
            Sprint = 1.20,
            Subsumed = "Lull",
            Introduced = "24.2",
            Themes = "Monk, Pacifist",
            Sex = "Male",
            MainCost = {
                Credits = 25000,
                BPStanding = 5000,
                MarketCost =  325,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 50,
                Time = 12,
                Parts = {
                    { Name = "Sola Toroid",Type = "Resource",Count = 3,},
                    { Name = "Alloy Plate",Type = "Resource",Count = 2850,},
                    { Name = "Hespazym Alloy",Type = "Resource",Count = 50,},
                    { Name = "Synathid Ecosynth Analyzer",Type = "Resource",Count = 5,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 50,
                Time = 12,
                Parts = {
                    { Name = "Vega Toroid",Type = "Resource",Count = 3,},
                    { Name = "Salvage",Type = "Resource",Count = 3250,},
                    { Name = "Hespazym Alloy",Type = "Resource",Count = 100,},
                    { Name = "Marquise Thyst",Type = "Resource",Count = 5,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Calda Toroid",Type = "Resource",Count = 3,},
                    { Name = "Ferrite",Type = "Resource",Count = 2500,},
                    { Name = "Tromyzon Entroplasma",Type = "Resource",Count = 10,},
                    { Name = "Radiant Zodian",Type = "Resource",Count = 5,},},
            },
        },
        ["Chroma"] = {
            Armor = 350,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "ChromaNewLook.png",
            Portrait = "ChromaIcon272.png",
            Name = "Chroma",
            Polarities = {"Bar", "V"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Elemental Ward",
            Introduced = "16",
            Themes = "Dragon, Elemental Power, Hunter",
            Sex = "Male",
            MainCost = {
                Credits = 25000,
                MarketCost =  375,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Volt Neuroptics",Type = "WarframePart",Count = 1},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 50,
                Time = 12,
                Parts = {
                    { Name = "Plastids",Type = "Resource",Count = 200,},
                    { Name = "Neural Sensors",Type = "Resource",Count = 2,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 350,},
                    { Name = "Ember Neuroptics",Type = "WarframePart",Count = 1},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 50,
                Time = 12,
                Parts = {
                    { Name = "Neurodes",Type = "Resource",Count = 2,},
                    { Name = "Salvage",Type = "Resource",Count = 900,},
                    { Name = "Plastids",Type = "Resource",Count = 50,},
                    { Name = "Frost Chassis",Type = "WarframePart",Count = 1},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Oxium",Type = "Resource",Count = 400,},
                    { Name = "Argon Crystal",Type = "Resource",Count = 2,},
                    { Name = "Neurodes",Type = "Resource",Count = 1,},
                    { Name = "Saryn Systems",Type = "WarframePart",Count = 1},},
            },
        },
        ["Chroma Prime"] = {
            Armor = 425,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 200,
            Health = 100,
            Image = "ChromaPrime.png",
            Portrait = "Chroma PrimeIcon272.png",
            Mastery = 6,
            Name = "Chroma Prime",
            Polarities = {"Bar", "D", "V", "Bar"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Elemental Ward",
            Introduced = "23.9",
            Themes = "Dragon, Elemental Power, Hunter",
            Sex = "Male",
            Vaulted = true,
        },
        ["Ember"] = {
            Armor = 125,
            AuraPolarity = "V",
            Conclave = false,
            Energy = 150,
            Health = 100,
            Image = "EmberNewLook.png",
            Portrait = "EmberIcon272.png",
            Name = "Ember",
            Polarities = {"Bar", "Bar"},
            Shield = 100,
            Sprint = 1.1,
            Subsumed = "Fire Blast",
            Introduced = "Vanilla",
            Themes = "Fire Elemental",
            Sex = "Female",
        },
        ["Ember Prime"] = {
            Armor = 150,
            AuraPolarity = "V",
            Conclave = false,
            Energy = 150,
            Health = 100,
            Image = "EmberPrimeNewLook.png",
            Portrait = "Ember PrimeIcon272.png",
            Name = "Ember Prime",
            Polarities = {"V", "D"},
            Shield = 125,
            Sprint = 1.1,
            Subsumed = "Fire Blast",
            Introduced = "11",
            Themes = "Fire Elemental",
            Sex = "Female",
            Vaulted = true,
        },
        ["Equinox"] = {
            Armor = 125,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Name = "Equinox",
            Portrait = "EquinoxIcon272.png",
            Polarities = {"D", "V"},
            Shield = 100,
            Sprint = 1.15,
            Subsumed = "Rest & Rage",
            Introduced = "17",
            Themes = "Duality, Day & Night",
            Sex = "Female",
        },
        ["Equinox Prime"] = {
            Mastery = 5,
            Armor = 150,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 165,
            Health = 125,
            Name = "Equinox Prime",
            Portrait = "EquinoxPrimeIcon.png",
            Polarities = {"D", "D", "V", "V"},
            Shield = 100,
            Sprint = 1.15,
            Subsumed = "Rest & Rage",
            Introduced = "24.5.8",
            Themes = "Duality, Day & Night",
            Sex = "Female",
            Vaulted = true,
        },
        ["Excalibur"] = {
            Armor = 225,
            AuraPolarity = "None",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "ExcaliburNewLook.png",
            Portrait = "ExcaliburIcon272.png",
            Name = "Excalibur",
            Polarities = {"D", "V"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Radial Blind",
            Introduced = "Vanilla",
            Themes = "Swordsman",
            Sex = "Male",
        },
        ["Excalibur Prime"] = {
            Armor = 300,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "ExcaliburPrimeNewLook.png",
            Portrait = "Excalibur PrimeIcon272.png",
            Name = "Excalibur Prime",
            Polarities = {"D", "V", "V"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Radial Blind",
            Introduced = "5",
            Themes = "Swordsman",
            Sex = "Male",
            Vaulted = "N/A",
        },
        ["Excalibur Umbra"] = {
            Armor = 300,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "ExcaliburUmbra.png",
            Portrait = "Excalibur UmbraIcon272.png",
            Name = "Excalibur Umbra",
            Polarities = {"V", "U", "U", "U"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Radial Blind",
            Introduced = "23",
            Themes = "Shadow, Swordsman",
            Sex = "Male",
            Vaulted = "N/A",
        },
        ["Excalibur Umbra Prime"] = {
            Armor = 250,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "ExcaliburUmbraPrime.png",
            Portrait = "ExcaliburUmbra.png",
            Name = "Excalibur Umbra Prime",
            Polarities = {"D", "V", "V"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Radial Blind",
            Themes = "Shadow, Swordsman",
            Sex = "Male",
            Vaulted = "N/A",
        },
        ["Frost"] = {
            Armor = 300,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "FrostNewLook.png",
            Portrait = "FrostIcon272.png",
            Name = "Frost",
            Polarities = {"Bar", "D"},
            Shield = 150,
            Sprint = 0.95,
            Subsumed = "Ice Wave",
            Introduced = "6",
            Themes = "Ice Elemental",
            Sex = "Male",
        },
        ["Frost Prime"] = {
            Armor = 300,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "FrostPrimeNewLook.png",
            Portrait = "Frost PrimeIcon272.png",
            Name = "Frost Prime",
            Polarities = {"Bar", "D", "D"},
            Shield = 175,
            Sprint = 0.95,
            Subsumed = "Ice Wave",
            Introduced = "7.10",
            Themes = "Ice Elemental",
            Sex = "Male",
            Vaulted = true,
        },
        ["Gara"] = {
            Armor = 150,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "GaraNewLook.png",
            Portrait = "GaraIcon272.png",
            Name = "Gara",
            Polarities = {"V", "V"},
            Shield = 100,
            Sprint = 1.15,
            Subsumed = "Spectrorage",
            Introduced = "22",
            Themes = "Glass, Warrior",
            Sex = "Female",
        },
        ["Garuda"] = {
            Armor = 300,
            AuraPolarity = "V",
            Conclave = false,
            Energy = 120,
            EnergyRank30 = 270,
            Health = 100,
            Image = "Garuda.png",
            Portrait = "GarudaIcon272.png",
            Name = "Garuda",
            Polarities = {"Bar", "D"},
            Shield = 100,
            Sprint = 1.00,
            Subsumed = "Blood Altar",
            Introduced = "24",
            Themes = "Blood Manipulation, Gore",
            Sex = "Female",
        },
        ["Gauss"] = {
            Armor = 175,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 150,
            ExilusPolarity = "Bar",
            Health = 100,
            Image = "Gauss.png",
            Portrait = "GaussIcon272.png",
            Name = "Gauss",
            Polarities = {"V", "D"},
            Shield = 150,
            Sprint = 1.4,
            Subsumed = "Thermal Sunder",
            Introduced = "25.7",
            Themes = "Kinetic Energy, Runner",
            Sex = "Male",
            MainCost = {
                Credits = 25000,
                BPCost = 30000,
                MarketCost = 275,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 3,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Argon Crystal",Type = "Resource",Count = 1,},
                    { Name = "Rubedo",Type = "Resource",Count = 1600,},
                    { Name = "Salvage",Type = "Resource",Count = 6200,},
                    { Name = "Alloy Plate",Type = "Resource",Count = 2950,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Radian Sentirum",Type = "Resource",Count = 3,},
                    { Name = "Heart Nyth",Type = "Resource",Count = 3,},
                    { Name = "Star Crimzian",Type = "Resource",Count = 6,},
                    { Name = "Grokdrul",Type = "Resource",Count = 55},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Radiant Zodian",Type = "Resource",Count = 3,},
                    { Name = "Marquise Thyst",Type = "Resource",Count = 3,},
                    { Name = "Mytocardia Spore",Type = "Resource",Count = 70,},
                    { Name = "Thermal Sludge",Type = "Resource",Count = 85,},},
            },
        },
        ["Grendel"] = {
            Armor = 350,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 150,
            Health = 350,
            Image = "Grendel.png",
            Portrait = "GrendelIcon272.png",
            Name = "Grendel",
            Polarities = {"Bar", "D", "D"},
            Shield = 25,
            Sprint = 0.95,
            Subsumed = "Nourish",
            Introduced = "26",
            Themes = "Hunger, Gluttony, Oni",
            Sex = "Male",
            MainCost = {
                Credits = 35000,
                MarketCost = 325,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 3,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Argon Crystal",Type = "Resource",Count = 2,},
                    { Name = "Control Module",Type = "Resource",Count = 5,},
                    { Name = "Ferrite",Type = "Resource",Count = 3500,},
                    { Name = "Alloy Plate",Type = "Resource",Count = 3800,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Condroc Wing",Type = "Resource",Count = 25,},
                    { Name = "Kuaka Spinal Claw",Type = "Resource",Count = 30,},
                    { Name = "Tralok Eyes",Type = "Resource",Count = 20,},
                    { Name = "Murkray Liver",Type = "Resource",Count = 15},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Circuits",Type = "Resource",Count = 1125,},
                    { Name = "Morphics",Type = "Resource",Count = 10,},
                    { Name = "Fish Meat",Type = "Resource",Count = 125,},
                    { Name = "Fish Oil",Type = "Resource",Count = 100,},},
            },
        },
        ["Harrow"] = {
            Armor = 175,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "Harrow.png",
            Portrait = "HarrowIcon272.png",
            Name = "Harrow",
            Polarities = {"D", "Bar"},
            Shield = 150,
            Sprint = 1,
            Subsumed = "Condemn",
            Introduced = "21",
            Themes = "Monastic, Void Manipulation",
            Sex = "Male",
        },
        ["Hildryn"] = {
            Armor = 300,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 0,
            ExilusPolarity = "D",
            Health = 75,
            Image = "HildrynIcon272.png",
            Portrait = "HildrynIcon272.png",
            Name = "Hildryn",
            Polarities = {"D", "D"},
            Shield = 450,
            ShieldRank30 = 1575,
            Sprint = 1.00,
            Subsumed = "Pillage",
            Introduced = "24.4",
            Themes = "Shield Maiden",
            Sex = "Female",
        },
        ["Hydroid"] = {
            Armor = 225,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 125,
            Health = 100,
            Image = "HydroidNewLook.png",
            Portrait = "HydroidIcon272.png",
            Name = "Hydroid",
            Polarities = {"V", "Bar"},
            Shield = 125,
            Sprint = 1.05,
            Subsumed = "Tempest Barrage",
            Introduced = "13",
            Themes = "Pirate, Water Elemental",
            Sex = "Male",
        },
        ["Hydroid Prime"] = {
            Armor = 275,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "HydroidPrimeBust.png",
            Portrait = "Hydroid PrimeIcon272.png",
            Mastery = 5,
            Name = "Hydroid Prime",
            Polarities = {"V", "D", "Bar", "Bar"},
            Shield = 175,
            Sprint = 1.05,
            Subsumed = "Tempest Barrage",
            Introduced = "21.6",
            Themes = "Pirate, Water Elemental",
            Sex = "Male",
            Vaulted = true,
        },
        ["Inaros"] = {
            Armor = 225,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 100,
            ExilusPolarity = "Bar",
            Health = 550,
            HealthRank30 = 2200,
            Image = "InarosNewLook.png",
            Portrait = "InarosIcon272.png",
            Name = "Inaros",
            Polarities = {"D", "D"},
            Shield = 0,
            Sprint = 1,
            Subsumed = "Desiccation",
            Introduced = "18.5",
            Themes = "Mummy, Sand Elemental",
            Sex = "Male",
        },
        ["Inaros Prime"] = {
            Armor = 225,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 125,
            ExilusPolarity = "Bar",
            Health = 575,
            HealthRank30 = 2300,
            Image = "InarosPrime.png",
            Portrait = "InarosPrimeIcon272.png",
            Name = "Inaros Prime",
            Polarities = {"V", "D", "D"},
            Shield = 0,
            Sprint = 1.05,
            Subsumed = "Desiccation",
            Introduced = "28.2",
            Themes = "Mummy, Sand Elemental",
            Sex = "Male",
        },
        ["Ivara"] = {
            Armor = 100,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 175,
            Health = 75,
            Image = "IvaraNewLook.png",
            Portrait = "IvaraIcon272.png",
            Name = "Ivara",
            Polarities = {"D", "Bar"},
            Shield = 100,
            Sprint = 1.15,
            Subsumed = "Quiver",
            Introduced = "18",
            Themes = "Archer, Poison Frog",
            Sex = "Female",
        },
        ["Ivara Prime"] = {
            Armor = 125,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 200,
            Health = 75,
            Image = "IvaraPrime.png",
            Portrait = "Ivara_PrimeIcon272.png",
            Name = "Ivara Prime",
            Polarities = {"V", "D", "Bar"},
            Shield = 150,
            Sprint = 1.20,
            Subsumed = "Quiver",
            Introduced = "27.0.4",
            Themes = "Archer, Jellyfish",
            Sex = "Female",
            Vaulted = false,
        },
        ["Khora"] = {
            Armor = 275,
            AuraPolarity = "D",
            Conclave = true,
            ExilusPolarity = "Bar",
            Energy = 125,
            Health = 125,
            Image = "Khora.png",
            Portrait = "KhoraIcon272.png",
            Name = "Khora",
            Polarities = {"V", "Bar"},
            Shield = 100,
            Sprint = 1.05,
            Subsumed = "Ensnare",
            Introduced = "22.18.0",
            Themes = "Arachnid, Huntress & Companion, Metal Manipulation",
            Sex = "Female",
        },
        ["Lavos"] = {
            Armor = 450,
            ArmorRank30 = 675,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 0,
            Health = 200,
            Image = "Lavos-Arsenal.webp",
            Portrait = "LavosIcon272.png",
            Name = "Lavos",
            Polarities = {"D", "Bar"},
            Shield = 100,
            Sprint = 1.15,
            Subsumed = "Vial Rush",
            Introduced = "29.6",
            Themes = "Alchemy, Serpentine",
            Sex = "Male",
            MainCost = {
                Credits = 25000,
                MarketCost = 325,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 3,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Trapezium Xenorhast",Type = "Resource",Count = 6,},
                    { Name = "Copernics",Type = "Resource",Count = 3750,},
                    { Name = "Oxium",Type = "Resource",Count = 750,},
                    { Name = "Rubedo",Type = "Resource",Count = 2750,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Argon Crystal",Type = "Resource",Count = 2,},
                    { Name = "Nitain Extract",Type = "Resource",Count = 5,},
                    { Name = "Cryotic",Type = "Resource",Count = 1500,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 5500},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Cabochon Embolos",Type = "Resource",Count = 6,},
                    { Name = "Nano Spores",Type = "Resource",Count = 5500,},
                    { Name = "Hexenon",Type = "Resource",Count = 550,},
                    { Name = "Circuits",Type = "Resource",Count = 3000,},},
            },
        },
        ["Limbo"] = {
            Armor = 100,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "LimboNewLook.png",
            Portrait = "LimboIcon272.png",
            Name = "Limbo",
            Polarities = {"V", "V"},
            Shield = 75,
            Sprint = 1.15,
            Subsumed = "Banish",
            Introduced = "15",
            Themes = "Magician, Planes of Existence",
            Sex = "Male",
        },
        ["Limbo Prime"] = {
            Mastery = 4,
            Armor = 125,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 175,
            Health = 100,
            Image = "Limbo PrimeIcon272.png",
            Portrait = "Limbo PrimeIcon272.png",
            Name = "Limbo Prime",
            Polarities = {"V", "V", "Bar", "D"},
            Shield = 100,
            Sprint = 1.15,
            Subsumed = "Banish",
            Introduced = "23.0.3",
            Themes = "Magician, Planes of Existence",
            Sex = "Male",
            Vaulted = true,
        },
        ["Loki"] = {
            Armor = 100,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 75,
            Image = "LokiNewLook.png",
            Portrait = "LokiIcon272.png",
            Name = "Loki",
            Polarities = {"D", "V"},
            Shield = 75,
            Sprint = 1.25,
            Subsumed = "Decoy",
            Introduced = "Vanilla",
            Themes = "Trickster",
            Sex = "Male",
        },
        ["Loki Prime"] = {
            Armor = 125,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 175,
            Health = 75,
            Image = "LokiPrimeNewLook.png",
            Portrait = "Loki PrimeIcon272.png",
            Name = "Loki Prime",
            Polarities = {"D", "D", "V", "Bar"},
            Shield = 75,
            Sprint = 1.25,
            Subsumed = "Decoy",
            Introduced = "13.7",
            Themes = "Trickster",
            Sex = "Male",
            Vaulted = true,
        },
        ["Mag"] = {
            Armor = 100,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 125,
            Health = 75,
            Image = "MagNewLook.png",
            Portrait = "MagIcon272.png",
            Name = "Mag",
            Polarities = {"Bar", "Bar"},
            Shield = 150,
            Sprint = 1,
            Subsumed = "Pull",
            Introduced = "Vanilla",
            Themes = "Magnetism",
            Sex = "Female",
        },
        ["Mag Prime"] = {
            Armor = 125,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 175,
            Health = 100,
            Image = "MagPrimeNewLook.png",
            Portrait = "Mag PrimeIcon272.png",
            Name = "Mag Prime",
            Polarities = {"Bar", "Bar", "V"},
            Shield = 150,
            Sprint = 1,
            Subsumed = "Pull",
            Introduced = "10",
            Themes = "Magnetism",
            Sex = "Female",
            Vaulted = true,
        },
        ["Mesa"] = {
            Armor = 100,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 125,
            Image = "MesaLarge.png",
            Portrait = "MesaIcon272.png",
            Name = "Mesa",
            Polarities = {"Bar", "Bar"},
            Shield = 75,
            Sprint = 1.1,
            Subsumed = "Shooting Gallery",
            Introduced = "15.5",
            Themes = "Gunslinger",
            Sex = "Female",
        },
        ["Mesa Prime"] = {
            Armor = 125,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 125,
            Health = 135,
            Image = "MesaPrime.png",
            Portrait = "MesaPrimeIcon272.png",
            Mastery = 2,
            Name = "Mesa Prime",
            Polarities = {"Bar", "Bar", "D", "V"},
            Shield = 75,
            Sprint = 1.1,
            Subsumed = "Shooting Gallery",
            Introduced = "24.2.2",
            Themes = "Gunslinger",
            Sex = "Female",
            Vaulted = true,
        },
        ["Mirage"] = {
            Armor = 100,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 80,
            Image = "MirageNewLook.png",
            Portrait = "MirageIcon272.png",
            Name = "Mirage",
            Polarities = {"D", "V"},
            Shield = 80,
            Sprint = 1.2,
            Subsumed = "Eclipse",
            Introduced = "14",
            Themes = "Harlequin, Illusionist",
            Sex = "Female",
        },
        ["Mirage Prime"] = {
            Armor = 175,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 80,
            Image = "MiragePrimeNewLook.png",
            Portrait = "Mirage PrimeIcon272.png",
            Mastery = 8,
            Name = "Mirage Prime",
            Polarities = {"D", "D", "Bar", "V"},
            Shield = 110,
            Sprint = 1.2,
            Subsumed = "Eclipse",
            Introduced = "22.7",
            Themes = "Harlequin, Illusionist",
            Sex = "Female",
            Vaulted = true,
        },
        ["Nekros"] = {
            Armor = 100,
            AuraPolarity = "None",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "NekrosNewLook.png",
            Portrait = "NekrosIcon272.png",
            Name = "Nekros",
            Polarities = {"D", "V"},
            Shield = 90,
            Sprint = 1.1,
            Subsumed = "Terrify",
            Introduced = "10",
            Themes = "Darkness, Necromancy",
            Sex = "Male",
        },
        ["Nekros Prime"] = {
            Armor = 125,
            AuraPolarity = "None",
            Conclave = true,
            Energy = 125,
            Health = 100,
            Image = "NekrosPrimeNewLook.png",
            Portrait = "Nekros PrimeIcon272.png",
            Name = "Nekros Prime",
            Polarities = {"V", "D", "Bar"},
            Shield = 150,
            Sprint = 1.1,
            Subsumed = "Terrify",
            Introduced = "The Silver Grove 3",
            Themes = "Darkness, Necromancy",
            Sex = "Male",
            Vaulted = true,
        },
        ["Nezha"] = {
            Armor = 190,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 125,
            Image = "NezhaNewLook.png",
            Portrait = "NezhaIcon272.png",
            Name = "Nezha",
            Polarities = {"D", "V"},
            Shield = 50,
            Sprint = 1.15,
            Subsumed = "Fire Walker",
            Introduced = "18.1",
            Themes = "Third Lotus Prince",
            Sex = "Male",
        },
        ["Nezha Prime"] = {
            Armor = 250,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 150,
            Health = 125,
            Image = "NezhaPrime.png",
            Portrait = "NezhaPrimeIcon272.png",
            Name = "Nezha Prime",
            Polarities = {"D", "V", "Bar"},
            Shield = 50,
            Sprint = 1.20,
            Subsumed = "Fire Walker",
            Introduced = "29.3",
            Themes = "Third Lotus Prince",
            Sex = "Male",
        },
        ["Nidus"] = {
            Armor = 300.0,
            ArmorRank30 = 450,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 150,
            Image = "NidusNewLook.png",
            Portrait = "NidusIcon272.png",
            Name = "Nidus",
            Polarities = {"V", "D"},
            Shield = 0,
            Sprint = 1,
            Subsumed = "Larva",
            Introduced = "19.5",
            Themes = "Infestation, Mutation",
            Sex = "Male",
        },
        ["Nova"] = {
            Armor = 100,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "NovaNewLook.png",
            Portrait = "NovaIcon272.png",
            Name = "Nova",
            Polarities = {"V", "V"},
            Shield = 75,
            Sprint = 1.2,
            Subsumed = "Null Star",
            Introduced = "9",
            Themes = "Antimatter Manipulation",
            Sex = "Female",
        },
        ["Nova Prime"] = {
            Armor = 125,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 175,
            Health = 100,
            Image = "NovaPrimeNewLook.png",
            Portrait = "Nova PrimeIcon272.png",
            Name = "Nova Prime",
            Polarities = {"V", "V", "V"},
            Shield = 100,
            Sprint = 1.2,
            Subsumed = "Null Star",
            Introduced = "15.7",
            Themes = "Antimatter Manipulation",
            Sex = "Female",
            Vaulted = true,
        },
        ["Nyx"] = {
            Armor = 100,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "NyxNewLook.png",
            Portrait = "NyxIcon272.png",
            Name = "Nyx",
            Polarities = {"V", "Bar"},
            Shield = 100,
            Sprint = 1.1,
            Subsumed = "Mind Control",
            Introduced = "6",
            Themes = "Psychic",
            Sex = "Female",
        },
        ["Nyx Prime"] = {
            Armor = 125,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "NyxPrimeNewLook.png",
            Portrait = "Nyx PrimeIcon272.png",
            Name = "Nyx Prime",
            Polarities = {"V", "Bar", "D"},
            Shield = 125,
            Sprint = 1.125,
            Subsumed = "Mind Control",
            Introduced = "14.8",
            Themes = "Psychic",
            Sex = "Female",
            Vaulted = true,
        },
        ["Oberon"] = {
            Armor = 175,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 125,
            Image = "OberonNewLook.png",
            Portrait = "OberonIcon272.png",
            Name = "Oberon",
            Polarities = {"V", "V"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Smite",
            Introduced = "11.5",
            Themes = "Nature, Paladin",
            Sex = "Male",
        },
        ["Oberon Prime"] = {
            Armor = 225,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 175,
            Health = 125,
            Image = "OberonPrimeBust.png",
            Portrait = "Oberon PrimeIcon272.png",
            Mastery = 8,
            Name = "Oberon Prime",
            Polarities = {"Bar", "Bar", "V", "V"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Smite",
            Introduced = "20.6.2",
            Themes = "Nature, Paladin",
            Sex = "Male",
            Vaulted = true,
        },
        ["Octavia"] = {
            Armor = 150,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "Octavia.png",
            Portrait = "OctaviaIcon272.png",
            Name = "Octavia",
            Polarities = {"Bar", "Bar"},
            Shield = 75,
            Sprint = 1.05,
            Subsumed = "Resonator",
            Introduced = "20",
            Themes = "Bard, Musician",
            Sex = "Female",
        },
        ["Octavia Prime"] = {
            Armor = 150,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 175,
            Health = 100,
            Image = "OctaviaPrime-Arsenal.webp",
            Portrait = "Octavia_PrimeIcon272.png",
            Name = "Octavia Prime",
            Polarities = {"D", "Bar", "Bar"},
            Shield = 100,
            Sprint = 1.05,
            Subsumed = "Resonator",
            Introduced = "29.9",
            Themes = "Bard, Musician",
            Sex = "Female",
            MainCost = {
                Credits = 25000,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 5,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Neural Sensors",Type = "Resource",Count = 8,},
                    { Name = "Control Module",Type = "Resource",Count = 10,},
                    { Name = "Oxium",Type = "Resource",Count = 250,},
                	{ Name = "Salvage",Type = "Resource",Count = 3750},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Argon Crystal",Type = "Resource",Count = 2,},
                    { Name = "Morphics",Type = "Resource",Count = 8,},
                    { Name = "Rubedo",Type = "Resource",Count = 1200,},
                    { Name = "Ferrite",Type = "Resource",Count = 4250,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Nitain Extract",Type = "Resource",Count = 2,},
                    { Name = "Cryotic",Type = "Resource",Count = 370,},
                    { Name = "Circuits",Type = "Resource",Count = 875,},
                    { Name = "Nano Spores",Type = "Resource",Count = 4800,},},
            },
        },
        ["Protea"] = {
            Armor = 125,
            AuraPolarity = "Aura",
            Conclave = false,
            Energy = 150,
            Health = 100,
            Image = "Protea.png",
            Portrait = "ProteaIcon272.png",
            Name = "Protea",
            Polarities = {"V", "Bar"}, 
            Shield = 150,
            Sprint = 1.20,
            Subsumed = "Dispensary",
            Introduced = "28",
            Themes = "Gadgetry, Time Manipulation",
            Sex = "Female",
            MainCost = {
                Credits = 25000,
                BPCost = 35000,
                MarketCost = 325,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 3,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Salvage",Type = "Resource",Count = 11500,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 5150,},
                    { Name = "Cubic Diodes",Type = "Resource",Count = 1250,},
                    { Name = "Neural Sensors",Type = "Resource",Count = 5,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Alloy Plate",Type = "Resource",Count = 20000,},
                    { Name = "Carbides",Type = "Resource",Count = 2750,},
                    { Name = "Oxium",Type = "Resource",Count = 550,},
                    { Name = "Morphics",Type = "Resource",Count = 12,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Ferrite",Type = "Resource",Count = 13400,},
                    { Name = "Cryotic",Type = "Resource",Count = 1000,},
                    { Name = "Copernics",Type = "Resource",Count = 3500,},
                    { Name = "Control Module",Type = "Resource",Count = 10,},},
            },
        },
        ["Revenant"] = {
            Armor = 125,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 125,
            Health = 100,
            Image = "Revenant.png",
            Name = "Revenant",
            Polarities = {"V", "D"},
            Portrait = "RevenantIcon272.png",
            Sex = "Male",
            Shield = 225,
            Sprint = 1.00,
            Subsumed = "Reave",
            Introduced = "23.5",
            Themes = "Eidolon, Vampirism",
            MainCost = {
                Credits = 25000,
                MarketCost = 325,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Neural Sensors",Type = "Resource",Count = 3,},
                    { Name = "Intact Sentient Core",Type = "Resource",Count = 15,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 6000,},
                    { Name = "Rubedo",Type = "Resource",Count = 2200,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Morphics",Type = "Resource",Count = 3,},
                    { Name = "Intact Sentient Core",Type = "Resource",Count = 10,},
                    { Name = "Rubedo",Type = "Resource",Count = 1500,},
                    { Name = "Iradite",Type = "Resource",Count = 50,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Control Module",Type = "Resource",Count = 3,},
                    { Name = "Cetus Wisp",Type = "Resource",Count = 3,},
                    { Name = "Salvage",Type = "Resource",Count = 8000,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 3000,},},
            },
        },
        ["Rhino"] = {
            Armor = 225,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "RhinoNewLook.png",
            Portrait = "RhinoIcon272.png",
            Name = "Rhino",
            Polarities = {"D", "D"},
            Shield = 150,
            Sprint = 0.95,
            Subsumed = "Roar",
            Introduced = "Vanilla",
            Themes = "Rhinoceros",
            Sex = "Male",
        },
        ["Rhino Prime"] = {
            Armor = 275,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "RhinoPrimeNewLook.png",
            Portrait = "Rhino PrimeIcon272.png",
            Name = "Rhino Prime",
            Polarities = {"D", "D", "Bar"},
            Shield = 150,
            Sprint = 1,
            Subsumed = "Roar",
            Introduced = "12.4",
            Themes = "Rhinoceros",
            Sex = "Male",
            Vaulted = true,
        },
        ["Saryn"] = {
            Armor = 225,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 150,
            Health = 125,
            Image = "SarynNewLook.png",
            Portrait = "SarynIcon272.png",
            Name = "Saryn",
            Polarities = {"Bar", "D"},
            Shield = 100,
            Sprint = 0.95,
            Subsumed = "Molt",
            Introduced = "7",
            Themes = "Disease, Poison, Serpentine",
            Sex = "Female",
        },
        ["Saryn Prime"] = {
            Armor = 300,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 200,
            Health = 125,
            Image = "SarynPrimeLarge.png",
            Portrait = "Saryn PrimeIcon272.png",
            Name = "Saryn Prime",
            Polarities = {"Bar", "D", "V"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Molt",
            Introduced = "18.4.12",
            Themes = "Disease, Poison, Serpentine",
            Sex = "Female",
            Vaulted = true,
        },
        ["Titania"] = {
            Armor = 100,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "TitaniaNewLook.png",
            Portrait = "TitaniaIcon272.png",
            Name = "Titania",
            Polarities = {"V", "D"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Spellbind",
            Introduced = "The Silver Grove",
            Themes = "Fairy Queen",
            Sex = "Female",
        },
        ["Titania Prime"] = {
            Mastery = 2,
            Armor = 125,
            AuraPolarity = "V",
            --Conclave = true,
            Energy = 175,
            Health = 125,
            Image = "TitaniaPrimeMain.png",
            Portrait = "TitaniaPrimeMain.png",
            Name = "Titania Prime",
            Polarities = {"Bar", "V", "V", "D"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Spellbind",
            Introduced = "27.3.6",
            Themes = "Fairy Queen",
            Sex = "Female",
        },
        ["Trinity"] = {
            Armor = 100,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "TrinityNewLook.png",
            Portrait = "TrinityIcon272.png",
            Name = "Trinity",
            Polarities = {"D", "D"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Well Of Life",
            Introduced = "Vanilla",
            Themes = "Healer",
            Sex = "Female",
        },
        ["Trinity Prime"] = {
            Armor = 125,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "TrinityPrimeMain.png",
            Portrait = "Trinity PrimeIcon272.png",
            Name = "Trinity Prime",
            Polarities = {"D", "D", "V", "Bar"},
            Shield = 150,
            Sprint = 1.1,
            Subsumed = "Well Of Life",
            Introduced = "17.6",
            Themes = "Healer",
            Sex = "Female",
            Vaulted = true,
        },
        ["Valkyr"] = {
            Armor = 600,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "ValkyrNewLook.png",
            Portrait = "ValkyrIcon272.png",
            Name = "Valkyr",
            Polarities = {"V", "V"},
            Shield = 50,
            Sprint = 1.1,
            Subsumed = "Warcry",
            Introduced = "11",
            Themes = "Berserker, Feline",
            Sex = "Female",
        },
        ["Valkyr Prime"] = {
            Armor = 700,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "ValkyrPrimeProfilePicture.png",
            Portrait = "Valkyr PrimeIcon272.png",
            Name = "Valkyr Prime",
            Polarities = {"V", "V", "V"},
            Shield = 50,
            Sprint = 1.1,
            Subsumed = "Warcry",
            Introduced = "19.0.7",
            Themes = "Berserker, Feline",
            Sex = "Female",
            Vaulted = true,
        },
        ["Vauban"] = {
            Armor = 150,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 150,
            Health = 100,
            Image = "VaubanNewLook.png",
            Portrait = "VaubanIcon272.png",
            Name = "Vauban",
            Polarities = {"Bar", "V"},
            Shield = 75,
            Sprint = 1,
            Subsumed = "Tesla Nervos",
            Introduced = "7.11",
            Themes = "Combat Engineer",
            Sex = "Male",
        },
        ["Vauban Prime"] = {
            Armor = 200,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 150,
            Health = 100,
            Image = "VaubanPrimeNewLook.png",
            Portrait = "Vauban PrimeIcon272.png",
            Name = "Vauban Prime",
            Polarities = {"Bar", "V", "D"},
            Shield = 100,
            Sprint = 1,
            Subsumed = "Tesla Nervos",
            Introduced = "18.12",
            Themes = "Combat Engineer",
            Sex = "Male",
            Vaulted = true,
        },
        ["Volt"] = {
            Armor = 100,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "VoltNewLook.png",
            Portrait = "VoltIcon272.png",
            Name = "Volt",
            Polarities = {"Bar", "V"},
            Shield = 150,
            Sprint = 1,
            Subsumed = "Shock",
            Introduced = "Vanilla",
            Themes = "Electricity",
            Sex = "Male",
        },
        ["Volt Prime"] = {
            Armor = 125,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 200,
            Health = 100,
            Image = "VoltPrimeLarge.png",
            Portrait = "Volt PrimeIcon272.png",
            Name = "Volt Prime",
            Polarities = {"Bar", "V", "V"},
            Shield = 150,
            Sprint = 1,
            Subsumed = "Shock",
            Introduced = "16.1",
            Themes = "Electricity",
            Sex = "Male",
            Vaulted = true,
        },
        ["Wisp"] = {
            Armor = 175,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 200,
            Health = 100,
            Image = "WispIcon272.png",
            Portrait = "WispIcon272.png",
            Name = "Wisp",
            Polarities = {"V", "D"},
            Shield = 75,
            Sprint = 1.2,
            Subsumed = "Breach Surge",
            Introduced = "25.0",
            Themes = "Will-O-Wisps, Portal Manipulation",
            Sex = "Female",
            MainCost = {
                Credits = 25000,
                MarketCost = 375,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 3,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Hexenon",Type = "Resource",Count = 300,},
                    { Name = "Tellurium",Type = "Resource",Count = 2,},
                    { Name = "Plastids",Type = "Resource",Count = 950,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 2200,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Hexenon",Type = "Resource",Count = 500,},
                    { Name = "Argon Crystal",Type = "Resource",Count = 1,},
                    { Name = "Oxium",Type = "Resource",Count = 700,},
                    { Name = "Alloy Plate",Type = "Resource",Count = 2750,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Hexenon",Type = "Resource",Count = 400,},
                    { Name = "Nitain Extract",Type = "Resource",Count = 2,},
                    { Name = "Rubedo",Type = "Resource",Count = 950,},
                    { Name = "Salvage",Type = "Resource",Count = 10000,},},
            },
        },
        ["Wukong"] = {
            Armor = 250,
            AuraPolarity = "V",
            Conclave = false,
            Energy = 120,
            Health = 150,
            Image = "WukongNewIcon.png",
            Portrait = "WukongIcon272.png",
            Name = "Wukong",
            Polarities = {"Bar", "D"},
            Shield = 100,
            Sprint = 1.00,
            Subsumed = "Defy",
            Introduced = "17.12",
            Themes = "Monkey King",
            Sex = "Male",
        },
        ["Wukong Prime"] = {
            Armor = 275,
            AuraPolarity = "V",
            Conclave = false,
            Energy = 130,
            Health = 150,
            Image = "WukongPrimeNewLook.png",
            Portrait = "Wukong_PrimeIcon272.png",
            Mastery = 5,
            MainCost = {
                Credits = 25000,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Prime Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Prime Chassis",Type = "Item",Count = 1,},
                    { Name = "Prime Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 5,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Neurodes",Type = "Resource",Count = 4,},
                    { Name = "Rubedo",Type = "Resource",Count = 750,},
                    { Name = "Plastids",Type = "Resource",Count = 200,},
                    { Name = "Alloy Plates",Type = "Resource",Count = 3550,}},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Argon Crystal",Type = "Resource",Count = 2,},
                    { Name = "Control Module",Type = "Resource",Count = 6,},
                    { Name = "Circuits",Type = "Resource",Count = 825,},
                    { Name = "Nano Spores",Type = "Resource",Count = 2200,}},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Nitain Extract",Type = "Resource",Count = 2,},
                    { Name = "Morphic",Type = "Resource",Count = 7,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 1150,},
                    { Name = "Ferrite",Type = "Resource",Count = 3800,}},
            },
            Name = "Wukong Prime",
            Polarities = {"Bar", "D", "V"},
            Shield = 120,
            Sprint = 1.05,
            Subsumed = "Defy",
            Introduced = "25.3.0",
            Themes = "Monkey King",
            Sex = "Male",
            Vaulted = false,
        },
        ["Xaku"] = {
            Armor = 137,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 153,
            Health = 97,
            Image = "Xaku.png",
            Mastery = 0,
            Name = "Xaku",
            Polarities = {"D", "D"},
            Portrait = "XakuIcon272.png",
            Sex = "",
            Shield = 89,
            Sprint = 1.02,
            Subsumed = "Xata's Whisper",
            Introduced = "29",
            Themes = "Broken, Void Manipulation",
            Vaulted = false,
            MainCost = {
                Credits = 25000,
                MarketCost = 325,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 3,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Neural Sensors",Type = "Resource",Count = 10,},
                    { Name = "Thaumic Distillate",Type = "Resource",Count = 60,},
                    { Name = "Sharrac Teeth",Type = "Resource",Count = 20,},
                    { Name = "Esher Devar",Type = "Resource",Count = 40,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Gyromag Systems",Type = "Resource",Count = 5,},
                    { Name = "Spinal Core Section",Type = "Resource",Count = 3,},
                    { Name = "Venerdo Alloy",Type = "Resource",Count = 50,},
                    { Name = "Lucent Teroglobe",Type = "Resource",Count = 50,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Breath Of The Eidolon",Type = "Resource",Count = 10,},
                    { Name = "Scintillant",Type = "Resource",Count = 5,},
                    { Name = "Pustulite",Type = "Resource",Count = 45,},
                    { Name = "Ganglion",Type = "Resource",Count = 60,},},
            },
        },
        ["Zephyr"] = {
            Armor = 100,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 100,
            Health = 150,
            Image = "ZephyrNewLook.png",
            Portrait = "ZephyrIcon272.png",
            Name = "Zephyr",
            Polarities = {"V", "Bar"},
            Shield = 150,
            Sprint = 1.15,
            Subsumed = "Airburst",
            Introduced = "12",
            Themes = "Air Elemental, Avian",
            Sex = "Female",
            MainCost = {
                Credits = 25000,
                BPCost = 35000,
                MarketCost = 275,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Circuits",Type = "Resource",Count = 150,},
                    { Name = "Oxium",Type = "Resource",Count = 200,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 200,},
                    { Name = "Salvage",Type = "Resource",Count = 500,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Oxium",Type = "Resource",Count = 200,},
                    { Name = "Nano Spores",Type = "Resource",Count = 900,},
                    { Name = "Rubedo",Type = "Resource",Count = 50,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Control Module",Type = "Resource",Count = 1,},
                    { Name = "Oxium",Type = "Resource",Count = 200,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 500,},
                    { Name = "Plastids",Type = "Resource",Count = 400,},},
            },
        },
        ["Zephyr Prime"] = {
            Mastery = 6,
            Armor = 125,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 150,
            Health = 150,
            Image = "ZephyrPrimeIcon.png",
            Portrait = "Zephyr PrimeIcon272.png",
            Name = "Zephyr Prime",
            Polarities = {"V", "V", "D", "Bar"},
            Shield = 150,
            Sprint = 1.20,
            Subsumed = "Airburst",
            Introduced = "22.16.4",
            Themes = "Air Elemental, Avian",
            Sex = "Female",
            Vaulted = true,
            MainCost = {
                Credits = 25000,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Prime Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Prime Chassis",Type = "Item",Count = 1,},
                    { Name = "Prime Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 5,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Neural Sensors",Type = "Resource",Count = 3,},
                    { Name = "Oxium",Type = "Resource",Count = 250,},
                    { Name = "Plastids",Type = "Resource",Count = 350,},
                    { Name = "Alloy Plate",Type = "Resource",Count = 4250,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Nitain Extract",Type = "Resource",Count = 2,},
                    { Name = "Tellurium",Type = "Resource",Count = 2,},
                    { Name = "Ferrite",Type = "Resource",Count = 3600,},
                    { Name = "Oxium",Type = "Resource",Count = 300,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Argon Crystal",Type = "Resource",Count = 2,},
                    { Name = "Neurodes",Type = "Resource",Count = 3,},
                    { Name = "Cryotic",Type = "Resource",Count = 550,},
                    { Name = "Nano Spores",Type = "Resource",Count = 3175,},},
            },
        },
    },
}

return WarframeData